import { expect, it } from 'vitest'
import { activityFieldChanges } from './activity'
import type { CampaignActivity } from '../../api/campaigns'
const entry = (patch: Partial<CampaignActivity>): CampaignActivity => ({ id: 1, at: '', actor_id: 'a', actor_display_name: 'Tom', table_name: 'pending_advances', action: 'update', reason: 'advancement', warband_id: 'w', warband_name: 'Dwarves', before: null, after: null, ...patch })
it('shows the app roll and subsequent manual change without field noise or chart instructions', () => {
 const rolled = { dice: [4, 6], text: 'Rolled 10: New Skill. Select one of the Skill tables', rollHistory: ['App rolled advancement dice: 3 + 6 = 9.', 'Manually changed first die: 3 → 4.'], rollChangeReason: 'Agreed correction' }
 const prose = activityFieldChanges(entry({ after: { rolled, revision: 1, resolved_at: null } })).map(c => c.sentence).join(' ')
 expect(prose).toContain('App rolled advancement dice: 3 + 6 = 9.')
 expect(prose).toContain('Manually changed first die: 3 → 4.')
 expect(prose).toContain('Agreed correction')
 expect(prose).not.toMatch(/Select one|revision|Changed rolled|none/)
})
it('does not repeat previously saved dice history when resolving an advance', () => {
 const rollHistory = ['App rolled advancement dice: 3 + 4 = 7.']
 const changes = activityFieldChanges(entry({ before: { rolled: { rollHistory } }, after: { resolution: { rollHistory, subjectName: 'Engineer', text: 'Rolled 7: +1 Weapon Skill, now WS5 Dice history: App rolled advancement dice: 3 + 4 = 7.' } } }))
 expect(changes.map(c => c.sentence)).toEqual(['Engineer: +1 Weapon Skill, now WS5'])
})
it('does not claim a historical final result was manually entered or generated by the app', () => {
 const prose = activityFieldChanges(entry({ after: { rolled: { dice: [4, 6], text: 'Rolled 10: New Skill. Select one of the Skill tables' } } })).map(c => c.sentence).join(' ')
 expect(prose).toContain('Recorded advancement total: 10.')
 expect(prose).toContain('original dice history was not recorded')
 expect(prose).not.toMatch(/Manually|App rolled|Select one/)
})
