import { useState } from 'react'
import { withRollAttempt, type BattleLiveState } from '../../../domain/battle'
import type { RosterWarband } from '../../../rules/types/roster'
import { Button, DieField, TextField } from '../../../ui'
import { WARMONGER } from './warmonger'
export function WarmongerControl({roster,sheet,edit,combatStarted}: {roster:RosterWarband;sheet:BattleLiveState;edit:(fn:(s:BattleLiveState)=>BattleLiveState)=>void;combatStarted:boolean}) {
 const [dice,setDice]=useState<[number|null,number|null]>([null,null]);const [die,setDie]=useState<number|null>(null);const [reason,setReason]=useState('')
 const hero=roster.heroes.find(h=>h.status==='active'&&h.unitTemplateId==='battle_monks_emissary'&&h.skillIds.includes(WARMONGER))
 if(!hero)return null
 const passed=dice.every(d=>d!==null)&&Number(dice[0])+Number(dice[1])<=hero.stats.Ld
 const saved=sheet.warmonger
 return <section className="flex flex-col gap-3 rounded-md border border-border p-4 text-sm"><h3 className="font-headline text-xl">Warmonger</h3>{saved?<><p>Leadership {saved.dice.join(' + ')} against Ld {saved.leadership}: {saved.count ? `${saved.count} free Raging Peasants join for this battle only.` : 'Failed; no extra Peasants join.'}</p>{!combatStarted?<details><summary>Correct this pre-battle result</summary><TextField label="Correction reason" value={reason} onChange={e=>setReason(e.target.value)}/><Button disabled={!reason.trim()} onClick={()=>edit(s=>withRollAttempt({...s,warmonger:undefined},{id:crypto.randomUUID(),at:new Date().toISOString(),turn:s.turn,kind:'attack',status:'complete',label:'Warmonger correction',rolls:[reason.trim()]}))}>Re-enter the test</Button></details>:null}</>:<><p>{hero.name} tests against Ld {hero.stats.Ld}. A success brings D3+1 Peasants, without payment or permanent recruitment.</p><div className="flex gap-3">{[0,1].map(i=><DieField key={i} label={`Warmonger D6 ${i+1}`} sides={6} rollable value={dice[i]} onChange={value=>setDice(d=>i===0?[value,d[1]]:[d[0],value])}/>)}</div>{passed?<DieField label="Warmonger D3" sides={3} rollable value={die} onChange={setDie}/>:null}<Button disabled={combatStarted||dice.some(d=>d===null)||(passed&&!die)} onClick={()=>{const result={groupId:crypto.randomUUID(),heroId:hero.id,dice:dice as [number,number],leadership:hero.stats.Ld,die:passed?die:null,count:passed?die!+1:0};edit(s=>s.warmonger?s:withRollAttempt({...s,warmonger:result},{id:crypto.randomUUID(),at:new Date().toISOString(),turn:s.turn,kind:'attack',status:'complete',label:`${hero.name}: Warmonger`,rolls:[`Leadership ${result.dice.join(' + ')} against ${result.leadership}. ${result.count ? `D3 ${die} + 1: ${result.count} free Peasants join this battle only.` : 'Failed; no extra Peasants.'}`]}))}}>Record Warmonger</Button></>}</section>
}
