import { EncampmentRewards } from './EncampmentRewards'
import { ForbiddenSquareRewards } from './ForbiddenSquareRewards'
import { GatheringRewards } from './GatheringRewards'
import { BrigandsRewards } from './BrigandsRewards'
import { HuntersRewards } from './HuntersRewards'
import { caravanRewards } from '../model/caravanRewards'
import { CaravanRewards } from './CaravanRewards'
import { DocksRewards } from './DocksRewards'
import { muleRewards } from '../model/muleRewards'
import { ritualZombies } from '../model/scenarioRecruits'
import { FerryRewards } from './FerryRewards'
import { RepeatedScenarioRewards } from './RepeatedScenarioRewards'
import { MAGICAL_ARTEFACTS } from '../../../rules/data/campaign/exploration'
import { Markdown, TextField, DieField, NumberField, SelectField } from '../../../ui'
import { scenarioRewardRule, type ScenarioRewardRule } from '../../../rules/data/campaign/scenarioRewardRules'
import { Card, Section } from '../../roster/view/bits'
import { scenarioHoardFinds, scenarioRewards, canKeepHeraldSword, type ScenarioRewardDraft } from '../model/scenarioRewards'
import type { StepProps } from './bits'

export function ScenarioRewards({ draft, derived, update, ctx, ruleOverride }: Pick<StepProps, 'draft' | 'derived' | 'update' | 'ctx'> & { ruleOverride?: ScenarioRewardRule }) {
  const rawRule = ruleOverride ?? scenarioRewardRule(ctx.scenarioId)
  const rule = rawRule?.kind === 'repeated' && rawRule.extraPerWarband ? { ...rawRule, requiredCount: (rawRule.requiredCount ?? 0) + rawRule.extraPerWarband * ((ctx.opponents?.length ?? 0) + 1) } : rawRule
  if (!rule) return null
  if (ctx.scenarioId === 'happy_harpy_hunting_grounds' && (draft.result !== 'won' || !draft.scenarioRewards?.harpy?.defeated)) return <Section title="Scenario rewards"><p className="text-sm text-ink-dim">No nest rewards: these require victory and all three Harpies defeated before the rival warbands routed.</p></Section>
  const state = draft.scenarioRewards ?? {}
  const reward = scenarioRewards(draft, ctx.scenarioId, derived.participants, ctx, ruleOverride)
  function change(fn: (s: ScenarioRewardDraft) => ScenarioRewardDraft) {
    update(d => ({ ...d, scenarioRewards: fn(d.scenarioRewards ?? {}) }))
  }
  const zombies = ritualZombies(draft, ctx, derived.injuries, derived.recruits)
  const heroes = derived.participants.heroes.filter(h => !draft.heroesOut.includes(h.id))
  const content = <>
    <p className="text-sm text-ink-dim">{rule.note}</p>
    {ctx.scenarioId === 'in_the_dead_of_the_night' && !ruleOverride ? <Card className="flex flex-col gap-3 px-4 py-3">
      <SelectField label="Did your defending warband complete the ritual?" value={state.ritualZombies?.completed === undefined ? '' : String(state.ritualZombies.completed)} onChange={e => change(s => ({ ...s, ritualZombies: { completed: e.target.value === '' ? undefined : e.target.value === 'true' } }))}><option value="">Choose…</option><option value="false">No — no summoned recruits</option><option value="true">Yes — resolve the summoned Zombies</option></SelectField>
      {state.ritualZombies?.completed ? <><DieField label="Summoned Zombies: D3 (+3)" sides={3} rollable value={state.ritualZombies.die ?? null} onChange={die => change(s => ({ ...s, ritualZombies: { ...s.ritualZombies, die, retain: null, groupIds: [] } }))} />{zombies.available !== null ? <NumberField label="Summoned Zombies to retain" hint={`${zombies.available} available; room for ${zombies.capacity}. New groups have at most five models.`} allowEmpty value={state.ritualZombies.retain ?? null} onChange={retain => change(s => ({ ...s, ritualZombies: { ...s.ritualZombies, retain, groupIds: Array.from({ length: Math.ceil(Math.min(6, Math.max(0, retain ?? 0)) / 5) }, () => crypto.randomUUID()) } }))} /> : null}</> : null}
      {zombies.problems.map(p => <p key={p} className="text-sm text-danger">{p}</p>)}
    </Card> : null}
    {rule.kind === 'ambush' ? <Card className="flex flex-col gap-3 px-4 py-3"><SelectField label="Was your warband the defender?" value={state.conditions?.defender === undefined ? '' : String(state.conditions.defender)} onChange={e => change(s => ({ ...s, conditions: { ...s.conditions, defender: e.target.value === '' ? undefined : e.target.value === 'true' } }))}><option value="">Choose…</option><option value="true">Yes</option><option value="false">No</option></SelectField><DieField label="Defender’s starting D6" sides={6} value={state.startingDie ?? null} onChange={startingDie => change(s => ({ ...s, startingDie }))} /><NumberField label="Defender’s starting Hero count" allowEmpty value={state.defendingHeroes ?? null} onChange={defendingHeroes => change(s => ({ ...s, defendingHeroes }))} />{state.conditions?.defender === false ? <NumberField label="Defending Heroes taken out by your warband" allowEmpty value={state.enemyHeroesOut ?? null} onChange={enemyHeroesOut => change(s => ({ ...s, enemyHeroesOut }))} /> : null}</Card> : null}
    {rule.kind === 'choice' ? <>
      <SelectField label={rule.question} value={state.branch ?? ''} onChange={e => change(() => ({ branch: e.target.value }))}><option value="">Choose…</option>{rule.options.map(o => <option key={o.id} value={o.id}>{o.label}</option>)}</SelectField>
      {rule.options.filter(o => o.id === state.branch).map(o => <ScenarioRewards key={o.id} draft={draft} derived={derived} update={update} ctx={ctx} ruleOverride={o.rule} />)}
    </> : null}
    {rule.kind === 'herald' ? <Card className="flex flex-col gap-3 px-4 py-3"><NumberField label="Star Stone splinters carried off by your warband" allowEmpty value={state.herald?.splinters ?? null} onChange={splinters => change(s => ({ ...s, herald: { ...s.herald, splinters } }))} /><SelectField label="Sword of the Herald outcome" value={state.herald?.sword ?? ''} onChange={e => change(s => ({ ...s, herald: { ...s.herald, sword: e.target.value as 'none' | 'sell' | 'keep', keepReason: '' } }))}><option value="">Choose…</option><option value="none">Our warband did not recover it</option><option value="sell">Hand it over — receive 100 gc</option><option value="keep">Keep the recovered sword</option></SelectField>{state.herald?.sword === 'keep' && !canKeepHeraldSword(ctx.roster.warbandTemplateId) ? <TextField label="Referee’s exception for keeping the sword" value={state.herald.keepReason ?? ''} onChange={e => change(s => ({ ...s, herald: { ...s.herald, keepReason: e.target.value } }))} /> : null}</Card> : null}
    {rule.kind === 'stake-out' && draft.result !== 'draw' ? <DieField label="Stake-Out income D6" sides={6} rollable value={state.stakeOut?.die ?? null} onChange={die => change(s => ({ ...s, stakeOut: { ...s.stakeOut, die } }))} /> : null}
    {rule.kind === 'recipe' ? <Card className="flex flex-col gap-3 px-4 py-3">
      <NumberField label="Unspoiled pies carried away by your warriors" allowEmpty value={state.recipe?.pies ?? null} onChange={pies => change(s => ({ ...s, recipe: { ...s.recipe, pies } }))} />
      {draft.result === 'won' ? <><NumberField label="Unspoiled pies claimed from the cart" allowEmpty value={state.recipe?.cartPies ?? null} onChange={cartPies => change(s => ({ ...s, recipe: { ...s.recipe, cartPies } }))} /><SelectField label="Is your warband turning Geefer in for the reward?" value={state.recipe?.turnsInGeefer === undefined ? '' : String(state.recipe.turnsInGeefer)} onChange={e => change(s => ({ ...s, recipe: { ...s.recipe, turnsInGeefer: e.target.value === '' ? undefined : e.target.value === 'true', dice: [] } }))}><option value="">Choose…</option><option value="true">Yes — we claim the payment</option><option value="false">No — another allied winner claims it</option></SelectField>{state.recipe?.turnsInGeefer ? <div className="flex flex-wrap gap-3">{Array.from({ length: 5 }, (_, i) => <DieField key={i} sides={6} rollable label={`Geefer payment: D6 ${i + 1}`} value={state.recipe?.dice?.[i] ?? null} onChange={v => change(s => ({ ...s, recipe: { ...s.recipe, dice: Array.from({ length: 5 }, (_, j) => i === j ? v : s.recipe?.dice?.[j] ?? null) } }))} />)}</div> : null}</> : null}
    </Card> : null}
    {rule.kind==='encampment'?<EncampmentRewards state={state.encampment??{}} won={draft.result==='won'} opponents={ctx.opponents??[]} change={encampment=>change(s=>({...s,encampment}))}/>:null}
    {rule.kind==='forbidden-square'?<ForbiddenSquareRewards state={state.forbiddenSquare??{}} warbands={ctx.opponents??[]} change={forbiddenSquare=>change(s=>({...s,forbiddenSquare}))}/>:null}
    {rule.kind==='gathering'?<GatheringRewards value={state.gathering??{}} won={draft.result==='won'} warbands={[{id:ctx.roster.id,name:ctx.roster.name},...(ctx.opponents??[])]} change={gathering=>change(s=>({...s,gathering}))}/>:null}
    {rule.kind === 'brigands' ? <BrigandsRewards state={state.brigands??{}} won={draft.result==='won'} campaign={!!ctx.campaignId} change={brigands=>change(s=>({...s,brigands}))}/> : null}
    {rule.kind === 'hunters' ? <HuntersRewards state={state.hunters??{}} won={draft.result==='won'} maxPlants={(ctx.opponents?new Set(ctx.opponents.map(o=>o.id)).size+1:6)*6} change={hunters=>change(s=>({...s,hunters}))}/> : null}
    {rule.kind === 'caravan' ? <>
      <CaravanRewards state={state.caravan ?? {}} archive={ctx.scenarioId === 'the_caravan_archive_pestilen'} result={draft.result} restricted={ctx.scenarioId === 'the_caravan' && !!ctx.campaignId && ctx.roster.scenarioEffects?.caravanBannedCampaigns.includes(ctx.campaignId)} change={caravan => change(s => ({ ...s, caravan, finds: {} }))} />
      {caravanRewards(state.caravan ?? {}, ctx.scenarioId === 'the_caravan_archive_pestilen', draft.result, ctx.campaignId, ctx.roster.scenarioEffects).rule ? <ScenarioRewards draft={draft} derived={derived} update={update} ctx={ctx} ruleOverride={caravanRewards(state.caravan ?? {}, ctx.scenarioId === 'the_caravan_archive_pestilen', draft.result, ctx.campaignId, ctx.roster.scenarioEffects).rule!} /> : null}
    </> : null}
    {rule.kind === 'docks' ? <DocksRewards state={state.docks ?? {}} participantCount={ctx.opponents ? new Set(ctx.opponents.map(o => o.id)).size + 1 : undefined} change={docks => change(s => ({ ...s, docks }))} /> : null}
    {rule.kind === 'mule-train' ? <>
      <SelectField label="Mule Train: your role" value={state.mule?.role ?? ''} onChange={e => change(s => ({ ...s, mule: { ...s.mule, role: e.target.value as 'attacker' | 'defender' }, finds: {} }))}><option value="">Choose…</option><option value="attacker">Attacker</option><option value="defender">Defender</option></SelectField>
      <NumberField label="Mules in the starting train" hint="3–6 mules, as set up for this battle" allowEmpty value={state.mule?.starting ?? null} onChange={starting => change(s => ({ ...s, mule: { ...s.mule, starting, recovered: null }, finds: {} }))} />
      <NumberField label="Mules your warband led safely off" allowEmpty value={state.mule?.recovered ?? null} onChange={recovered => change(s => ({ ...s, mule: { ...s.mule, recovered }, finds: {} }))} />
      {muleRewards(state.mule ?? {}).rule ? <ScenarioRewards draft={draft} derived={derived} update={update} ctx={ctx} ruleOverride={muleRewards(state.mule ?? {}).rule!} /> : null}
    </> : null}
    {rule.kind === 'ferry' ? <FerryRewards state={state.ferry ?? {}} won={draft.result === 'won'} change={ferry => change(s => ({ ...s, ferry }))} /> : null}
    {rule.kind === 'horses' ? <Card className="flex flex-col gap-3 px-4 py-3"><NumberField label="Successfully stolen horses before routing losses" allowEmpty value={state.horses ?? null} onChange={horses => change(s => ({ ...s, horses }))} />{draft.routed ? <DieField label="Horses lost: D3" sides={3} rollable value={state.lostHorsesDie ?? null} onChange={lostHorsesDie => change(s => ({ ...s, lostHorsesDie }))} /> : null}</Card> : null}
    {rule.kind === 'bounty' ? <>
      {rule.winnerOnly && draft.result !== 'won' ? <p className="text-sm text-ink-dim">No winning-warband bounty.</p> : <>
        {rule.condition ? <SelectField label={rule.condition.question} value={state.conditions?.[rule.condition.id] === undefined ? '' : String(state.conditions[rule.condition.id])} onChange={e => change(s => ({ ...s, conditions: { ...s.conditions, [rule.condition!.id]: e.target.value === '' ? undefined : e.target.value === 'true' }, bountyCount: null, bountyDice: [] }))}><option value="">Choose…</option><option value="true">Yes</option><option value="false">No</option></SelectField> : null}
        {!rule.condition || state.conditions?.[rule.condition.id] ? <Card className="flex flex-col gap-3 px-4 py-3"><NumberField label={rule.label} allowEmpty value={state.bountyCount ?? null} onChange={bountyCount => change(s => ({ ...s, bountyCount }))} hint={`${rule.goldEach} gc each`} />{rule.baseDice ? <div className="flex flex-wrap gap-3">{Array.from({ length: rule.baseDice.count }, (_, i) => <DieField key={i} label={`Base payment D6 ${i + 1}`} sides={6} rollable value={state.bountyDice?.[i] ?? null} onChange={v => change(s => ({ ...s, bountyDice: Array.from({ length: rule.baseDice!.count }, (_, j) => i === j ? v : s.bountyDice?.[j] ?? null) }))} />)}</div> : null}</Card> : null}
      </>}
    </> : null}
    {rule.kind === 'repeated' && (!rule.winnerOnly || draft.result === 'won') ? <RepeatedScenarioRewards rule={rule} state={state} change={change} /> : null}
    {rule.kind === 'repeated' && rule.bonusFinds && (!rule.winnerOnly || draft.result === 'won') ? <ScenarioRewards draft={draft} derived={derived} update={update} ctx={ctx} ruleOverride={{ kind: 'hoard', finds: rule.bonusFinds, note: 'Record the additional gold and gems, separate from the treasure table.', winnerOnly: rule.winnerOnly ?? false }} /> : null}
    {rule.kind === 'counters' ? <NumberField label={rule.label ?? 'Counters held at the end'} value={state.counters ?? 0} onChange={counters => change(s => ({ ...s, counters }))} hint={rule.note} /> : null}
    {rule.kind === 'building' ? <Card className="px-4 py-3">{heroes.map(h => <label key={h.id} className="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" checked={state.buildingHeroes?.includes(h.id) ?? false} onChange={e => change(s => ({ ...s, buildingHeroes: e.target.checked ? [...(s.buildingHeroes ?? []), h.id] : (s.buildingHeroes ?? []).filter(id => id !== h.id) }))} />{h.name} inside the objective building</label>)}{heroes.length === 0 ? <p className="text-sm text-ink-dim">No eligible Heroes.</p> : null}</Card> : null}
    {rule.kind === 'encounter' ? <Card className="flex flex-col gap-3 px-4 py-3"><div className="flex flex-wrap gap-3"><DieField label="Your starting shards (D3)" sides={3} rollable value={state.ownStarting ?? null} onChange={ownStarting => change(s => ({ ...s, ownStarting }))} /><DieField label="Opponent’s starting shards (D3)" sides={3} value={state.enemyStarting ?? null} onChange={enemyStarting => change(s => ({ ...s, enemyStarting }))} /></div><NumberField label="Enemy Heroes taken out of action" allowEmpty value={state.enemyHeroesOut ?? null} onChange={enemyHeroesOut => change(s => ({ ...s, enemyHeroesOut }))} hint="Count Heroes only, not every enemy casualty. Your own Hero casualties are taken from this report." /></Card> : null}
    {rule.kind === 'hoard' && rule.winnerOnly !== false && draft.result !== 'won' ? <p className="text-sm text-ink-dim">Only the winning warband receives this treasure.</p> : null}
    {rule.kind === 'hoard' && (rule.winnerOnly === false || draft.result === 'won') ? <>
      {rule.containers ? <Card className="px-4 py-3">{rule.containers.map(c => <label key={c.id} className="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" checked={state.containers?.includes(c.id) ?? false} onChange={e => change(s => ({ ...s, containers: e.target.checked ? [...(s.containers ?? []), c.id] : (s.containers ?? []).filter(id => id !== c.id), finds: Object.fromEntries(Object.entries(s.finds ?? {}).filter(([key]) => !key.startsWith(`${c.id}:`))) }))} />{c.label} carried to safety</label>)}</Card> : null}
      {rule.branches ? <SelectField label={rule.branches.question} value={state.branch ?? ''} onChange={e => change(s => ({ ...s, branch: e.target.value, finds: {} }))}><option value="">Choose…</option>{rule.branches.options.map(b => <option key={b.id} value={b.id}>{b.label}</option>)}</SelectField> : null}
      {rule.condition ? <SelectField label={rule.condition.question} value={state.conditions?.[rule.condition.id] === undefined ? '' : String(state.conditions[rule.condition.id])} onChange={e => change(s => ({ ...s, conditions: { ...s.conditions, [rule.condition!.id]: e.target.value === '' ? undefined : e.target.value === 'true' }, finds: {} }))}><option value="">Choose…</option><option value="true">Yes — resolve the hoard</option><option value="false">No — no hoard reward</option></SelectField> : null}
      {rule.needsRescue ? <SelectField label="Did the merchant’s son survive?" value={state.princeSurvived === undefined ? '' : String(state.princeSurvived)} onChange={e => change(s => ({ ...s, princeSurvived: e.target.value === '' ? undefined : e.target.value === 'true', finds: {} }))}><option value="">Choose…</option><option value="true">Yes — resolve the reward</option><option value="false">No — no reward</option></SelectField> : null}
      {(!rule.needsRescue || state.princeSurvived) && (!rule.condition || state.conditions?.[rule.condition.id]) ? scenarioHoardFinds(rule, draft, derived.participants).map(find => {
        const entry = state.finds?.[find.id]
        const discoveryCount = find.discoveryDice ?? 1
        const discoveries = discoveryCount === 1 ? [entry?.discovery ?? null] : entry?.discoveryDice ?? []
        const discoveryComplete = discoveries.length === discoveryCount && discoveries.every(d => d !== null)
        const available = !find.unclaimedBeforeBattle || state.unclaimedBooty?.[find.id] === true
        const found = available && (!find.threshold || (discoveryComplete && discoveries.reduce<number>((sum, d) => sum + (d ?? 0), 0) >= find.threshold))
        const quantity = find.quantity
        const choiceCount = typeof quantity === 'number' ? quantity : entry?.dice.length === quantity.count && entry.dice.every(d => d !== null && d >= 1 && d <= quantity.sides) ? entry.dice.reduce<number>((sum, d) => sum + d!, 0) * (quantity.multiplier ?? 1) + (quantity.bonus ?? 0) : 0
        return <Card key={find.id} className="flex flex-col gap-3 px-4 py-3"><div><h3 className="font-semibold">{find.label}</h3><p className="text-xs text-ink-dim">{find.chooseUpTo !== undefined ? 'Select only the relics you rescued' : find.unclaimedBeforeBattle ? 'Awarded only if not already found before the battle' : find.threshold ? `Found on a separate ${discoveryCount === 1 ? 'D6' : `${discoveryCount}D6`} roll of ${find.threshold}+` : 'Automatically found'}</p></div>
          {find.unclaimedBeforeBattle ? <SelectField label={`${find.label}: was this already found before the battle?`} value={state.unclaimedBooty?.[find.id] === undefined ? '' : String(state.unclaimedBooty[find.id])} onChange={e => change(s => ({ ...s, unclaimedBooty: { ...s.unclaimedBooty, [find.id]: e.target.value === '' ? undefined : e.target.value === 'true' }, finds: { ...s.finds, [find.id]: { discovery: null, dice: [] } } }))}><option value="">Choose…</option><option value="false">Yes — do not award it again</option><option value="true">No — claim it now</option></SelectField> : null}
          {find.threshold && discoveryCount === 1 ? <DieField label={`${find.label}: discovery D6`} sides={6} rollable value={entry?.discovery ?? null} onChange={discovery => change(s => ({ ...s, finds: { ...s.finds, [find.id]: { discovery, dice: [] } } }))} /> : null}
          {find.threshold && discoveryCount > 1 ? <div className="flex flex-wrap gap-3">{Array.from({ length: discoveryCount }, (_, i) => <DieField key={i} label={`${find.label}: discovery D6 ${i + 1}`} sides={6} rollable value={discoveries[i] ?? null} onChange={value => change(s => { const current = s.finds?.[find.id]; return { ...s, finds: { ...s.finds, [find.id]: { discovery: null, discoveryDice: Array.from({ length: discoveryCount }, (_, j) => i === j ? value : current?.discoveryDice?.[j] ?? null), dice: [] } } } })} />)}</div> : null}
          {found && find.multiplierRuling ? <div className="flex flex-col gap-3"><p className="text-sm text-ink-dim">{find.multiplierRuling}</p><NumberField label={`${find.label}: agreed multiplier`} allowEmpty value={entry?.multiplier ?? null} onChange={multiplier => change(s => ({ ...s, finds: { ...s.finds, [find.id]: { discovery: null, dice: [], ...s.finds?.[find.id], multiplier } } }))} /><TextField label={`${find.label}: multiplier ruling`} value={entry?.multiplierReason ?? ''} onChange={e => change(s => ({ ...s, finds: { ...s.finds, [find.id]: { discovery: null, dice: [], ...s.finds?.[find.id], multiplierReason: e.target.value } } }))} /></div> : null}
          {found && find.itemOptions && find.chooseUpTo !== undefined ? <div className="flex flex-col gap-2">{find.itemOptions.map(name => <label key={name} className="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" checked={entry?.items?.includes(name) ?? false} onChange={e => change(s => { const current = s.finds?.[find.id]; return { ...s, finds: { ...s.finds, [find.id]: { discovery: null, dice: [], ...current, items: e.target.checked ? [...(current?.items ?? []), name] : (current?.items ?? []).filter(n => n !== name) } } } })} />{name} rescued</label>)}</div> : null}
          {found && find.kind === 'artefact' ? <div className="flex flex-col gap-3"><p className="text-sm text-ink-dim">Each artefact may be found only once per campaign. Previously found results must be rerolled unless your table agrees an explained exception.</p><ul className="text-xs text-ink-dim">{MAGICAL_ARTEFACTS.map(a => { const previous = ctx.artefacts?.find(f => f.roll === a.band.min && (!ctx.reportId || f.reportId !== ctx.reportId)); return <li key={a.name}>{a.band.min}: {a.name} — {previous ? `found by ${previous.warbandName}` : ctx.artefacts ? 'not yet found' : 'checking campaign…'}</li> })}</ul><DieField label={`${find.label}: artefact D6`} sides={6} rollable value={entry?.artefactRoll ?? null} onChange={artefactRoll => change(s => ({ ...s, finds: { ...s.finds, [find.id]: { ...s.finds![find.id], artefactRoll, artefactOverrideReason: '' } } }))} />{MAGICAL_ARTEFACTS.filter(a => a.band.min === entry?.artefactRoll).map(a => <div key={a.name}><p className="font-semibold">{a.name}</p><Markdown source={a.text} /></div>)}<details><summary className="cursor-pointer text-sm">Agreed duplicate override</summary><TextField label={`${find.label}: duplicate override reason`} value={entry?.artefactOverrideReason ?? ''} onChange={e => change(s => ({ ...s, finds: { ...s.finds, [find.id]: { ...s.finds![find.id], artefactOverrideReason: e.target.value } } }))} /></details></div> : null}
          {found && !find.multiplierRuling && typeof quantity !== 'number' && (quantity.bonus || quantity.multiplier) ? <p className="text-sm text-ink-dim">{quantity.count}D{quantity.sides}{quantity.multiplier ? ` × ${quantity.multiplier}` : ''}{quantity.bonus ? ` + ${quantity.bonus}` : ''}{find.quantityIsValue ? ' gc value; the item stays in your stash.' : ` ${find.kind === 'gold' ? 'gc' : find.kind === 'shards' ? 'wyrdstone' : 'items'}, calculated from the dice below.`}</p> : null}
          {found && typeof quantity !== 'number' ? <div className="flex flex-wrap gap-3">{Array.from({ length: quantity.count }, (_, i) => <DieField key={i} label={`${find.label}: D${quantity.sides} ${i + 1}`} sides={quantity.sides} rollable value={entry?.dice[i] ?? null} onChange={value => change(s => { const current = s.finds?.[find.id]; return { ...s, finds: { ...s.finds, [find.id]: { ...current, discovery: current?.discovery ?? null, discoveryDice: current?.discoveryDice, items: [], unitValueDice: [], dice: Array.from({ length: quantity.count }, (_, j) => j === i ? value : current?.dice[j] ?? null) } } } })} />)}</div> : null}
          {found && find.itemOptions && find.chooseUpTo === undefined ? Array.from({ length: choiceCount }, (_, i) => <SelectField key={i} label={`${find.label}: dose ${i + 1}`} value={entry?.items?.[i] ?? ''} onChange={e => change(s => { const current = s.finds?.[find.id]; return { ...s, finds: { ...s.finds, [find.id]: { discovery: null, dice: [], ...current, items: Array.from({ length: choiceCount }, (_, j) => i === j ? e.target.value : current?.items?.[j] ?? '') } } } })}><option value="">Choose…</option>{find.itemOptions!.map(name => <option key={name} value={name}>{name}</option>)}</SelectField>) : null}
          {found && find.unitValueMultiplier ? Array.from({ length: choiceCount }, (_, i) => <DieField key={i} label={`${find.label}: gem ${i + 1} value D6`} sides={6} rollable value={entry?.unitValueDice?.[i] ?? null} onChange={value => change(s => { const current = s.finds?.[find.id]; return { ...s, finds: { ...s.finds, [find.id]: { discovery: null, dice: [], ...current, unitValueDice: Array.from({ length: choiceCount }, (_, j) => i === j ? value : current?.unitValueDice?.[j] ?? null) } } } })} />) : null}
          {find.threshold && discoveryComplete && !found ? <p className="text-sm text-ink-dim">Not found.</p> : null}
          {found && !find.itemOptions && find.kind !== 'artefact' && typeof quantity === 'number' ? <p className="text-sm">{quantity} {find.kind === 'gold' ? 'gc added to the treasury' : find.kind === 'shards' ? 'wyrdstone added to the treasury' : 'added to the stash'} when the report is filed.</p> : null}
        </Card>
      }) : null}
    </> : null}
    {!ruleOverride && rule.kind !== 'none' ? <p className="text-sm">Resolved rewards: {reward.gold} gc, {reward.shards} wyrdstone{reward.items.length ? `, ${reward.items.reduce((sum, item) => sum + item.quantity, 0)} items for the stash` : ''}. {reward.problems.length ? 'Complete the remaining entries before filing.' : 'The calculation will appear in the battle report.'}</p> : null}
  </>
  return ruleOverride ? <div className="flex flex-col gap-4">{content}</div> : <Section title="Scenario rewards">{content}</Section>
}
