-- #230: public bug and improvement boards, submissions, follows, merges, releases and private
-- notifications. Contract: docs/FEEDBACK-BATCH-2026-09-12.md. Public rows carry exactly the fields the
-- UI types declare (src/features/feedback/types.ts); anything private (who reported, who follows, the
-- submission ledger for rate limiting, who maintains) lives in its own table with its own policy.
-- Every write goes through a security-definer RPC so the rules below cannot be bypassed from a client.

-- ---------------------------------------------------------------------------------------------
-- Maintainers: managed by the service role only. No self-promotion; auth metadata is never trusted.
-- ---------------------------------------------------------------------------------------------
create table public.feedback_maintainers (
  user_id uuid primary key references auth.users (id) on delete cascade,
  added_at timestamptz not null default now()
);
comment on table public.feedback_maintainers is 'Who may review, merge and publish feedback. Rows are written by the service role only (no client policy).';
alter table public.feedback_maintainers enable row level security;
-- No policies: authenticated clients can neither read nor write; is_feedback_maintainer() answers for them.

create or replace function public.is_feedback_maintainer()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (select 1 from public.feedback_maintainers m where m.user_id = auth.uid());
$$;
revoke all on function public.is_feedback_maintainer() from public;
grant execute on function public.is_feedback_maintainer() to anon, authenticated;

/** True when the caller is the service role (server-side tooling), false for every signed-in or anonymous client. */
create or replace function public.is_service_role()
returns boolean
language sql
stable
set search_path = ''
as $$
  select coalesce(
    nullif(current_setting('request.jwt.claim.role', true), ''),
    (nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'role')
  ) = 'service_role';
$$;
revoke all on function public.is_service_role() from public;

-- ---------------------------------------------------------------------------------------------
-- Releases: drafts are maintainers-only; published releases are public. Version is unique.
-- ---------------------------------------------------------------------------------------------
create table public.feedback_releases (
  id uuid primary key default gen_random_uuid(),
  version text not null unique check (char_length(version) between 1 and 40),
  title text not null check (char_length(title) between 1 and 140),
  notes text not null default '' check (char_length(notes) <= 12000),
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
comment on table public.feedback_releases is 'Release changelog entries. Public once published_at is set; maintainers see drafts. Publishing goes through publish_feedback_release.';
create trigger feedback_releases_set_updated_at before update on public.feedback_releases for each row execute function public.set_updated_at();
alter table public.feedback_releases enable row level security;
create policy feedback_releases_select on public.feedback_releases
  for select to anon, authenticated using (published_at is not null or public.is_feedback_maintainer());
create policy feedback_releases_insert_maintainer on public.feedback_releases
  for insert to authenticated with check (public.is_feedback_maintainer() and published_at is null);
create policy feedback_releases_update_draft_maintainer on public.feedback_releases
  for update to authenticated
  using (public.is_feedback_maintainer() and published_at is null)
  with check (public.is_feedback_maintainer() and published_at is null);
create policy feedback_releases_delete_draft_maintainer on public.feedback_releases
  for delete to authenticated using (public.is_feedback_maintainer() and published_at is null);
grant select on public.feedback_releases to anon, authenticated;
grant insert, update, delete on public.feedback_releases to authenticated;

-- ---------------------------------------------------------------------------------------------
-- Issues: public readable, exactly the FeedbackIssue fields. Ids start at 232 so the imported
-- tracker entries 1–231 can keep their numbers. All writes are RPC-only.
-- ---------------------------------------------------------------------------------------------
create table public.feedback_issues (
  id bigint generated by default as identity (start with 232) primary key,
  kind text not null check (kind in ('bug', 'improvement')),
  title text not null check (char_length(title) between 5 and 140),
  notes text not null check (char_length(notes) between 10 and 12000),
  priority text not null default 'medium' check (priority in ('high', 'medium', 'low')),
  status text not null default 'reported' check (status in ('reported', 'reviewed', 'working_on', 'implemented', 'confirmed')),
  /** The reporter's profile display name at submission, or the maintainers' wording for imported entries. Never a raw account id. */
  reported_by text not null check (char_length(reported_by) between 1 and 60),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  release_id uuid references public.feedback_releases (id) on delete set null,
  duplicate_of bigint references public.feedback_issues (id) on delete set null,
  check (duplicate_of is null or duplicate_of <> id)
);
comment on table public.feedback_issues is 'Public bug and improvement board. Rows are created by submit_feedback and changed by review_feedback / merge_feedback / publish_feedback_release only.';
create index feedback_issues_status_idx on public.feedback_issues (status, priority, updated_at desc);
create index feedback_issues_release_idx on public.feedback_issues (release_id) where release_id is not null;
create index feedback_issues_duplicate_idx on public.feedback_issues (duplicate_of) where duplicate_of is not null;
create trigger feedback_issues_set_updated_at before update on public.feedback_issues for each row execute function public.set_updated_at();
alter table public.feedback_issues enable row level security;
create policy feedback_issues_select on public.feedback_issues for select to anon, authenticated using (true);
grant select on public.feedback_issues to anon, authenticated;

-- Who submitted what, for the rate limit and for the reporter's automatic follow. Private.
create table public.feedback_submissions (
  issue_id bigint primary key references public.feedback_issues (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  created_at timestamptz not null default now()
);
comment on table public.feedback_submissions is 'Private ledger of who submitted each issue (rate limiting, reporter follow). Not readable by clients.';
create index feedback_submissions_user_idx on public.feedback_submissions (user_id, created_at desc);
alter table public.feedback_submissions enable row level security;

-- Follows: a user reads only their own; follow/unfollow through the RPC so merges can move them.
create table public.feedback_subscriptions (
  user_id uuid not null references auth.users (id) on delete cascade,
  issue_id bigint not null references public.feedback_issues (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, issue_id)
);
comment on table public.feedback_subscriptions is 'Who follows which issue. The reporter follows automatically; merges move follows to the canonical issue.';
create index feedback_subscriptions_issue_idx on public.feedback_subscriptions (issue_id);
alter table public.feedback_subscriptions enable row level security;
create policy feedback_subscriptions_select_own on public.feedback_subscriptions
  for select to authenticated using (user_id = (select auth.uid()));
grant select on public.feedback_subscriptions to authenticated;

-- ---------------------------------------------------------------------------------------------
-- Notifications: private to their owner; written only by server-side RPCs (publishing today, #229
-- later). dedupe_key makes "exactly once per issue and release" a constraint, not a hope.
-- ---------------------------------------------------------------------------------------------
create table public.app_notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  kind text not null default 'feedback_release' check (char_length(kind) between 1 and 40),
  title text not null check (char_length(title) between 1 and 140),
  body text not null default '' check (char_length(body) <= 2000),
  href text not null default '' check (char_length(href) <= 300),
  dedupe_key text unique,
  created_at timestamptz not null default now(),
  read_at timestamptz
);
comment on table public.app_notifications is 'Private in-app inbox. Owners read and mark read (RPC); only server-side functions insert.';
create index app_notifications_user_idx on public.app_notifications (user_id, read_at, created_at desc);
alter table public.app_notifications enable row level security;
create policy app_notifications_select_own on public.app_notifications
  for select to authenticated using (user_id = (select auth.uid()));
grant select on public.app_notifications to authenticated;

-- ---------------------------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------------------------
/** Follow the duplicate chain to the issue that actually tracks the work (bounded; a cycle raises). */
create or replace function public.feedback_canonical(p_issue_id bigint)
returns bigint
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_id bigint := p_issue_id;
  v_next bigint;
  v_steps int := 0;
begin
  loop
    select duplicate_of into v_next from public.feedback_issues where id = v_id;
    if not found then raise exception 'feedback issue % not found', p_issue_id using errcode = 'P0002'; end if;
    if v_next is null then return v_id; end if;
    v_id := v_next; v_steps := v_steps + 1;
    if v_steps > 50 then raise exception 'duplicate chain too long or circular at issue %', p_issue_id using errcode = 'P0001'; end if;
  end loop;
end;
$$;
revoke all on function public.feedback_canonical(bigint) from public;
grant execute on function public.feedback_canonical(bigint) to anon, authenticated;

create or replace function public.require_feedback_maintainer()
returns void
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null or not public.is_feedback_maintainer() then
    raise exception 'only a feedback maintainer may do this' using errcode = '42501';
  end if;
end;
$$;
revoke all on function public.require_feedback_maintainer() from public;

-- ---------------------------------------------------------------------------------------------
-- submit_feedback: signed-in users report a bug or improvement. Public, attributed to the profile's
-- display name, reported / medium by default, ten an hour per user.
-- ---------------------------------------------------------------------------------------------
create or replace function public.submit_feedback(p_kind text, p_title text, p_notes text)
returns bigint
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_user uuid := auth.uid();
  v_title text := btrim(coalesce(p_title, ''));
  v_notes text := btrim(coalesce(p_notes, ''));
  v_name text;
  v_recent int;
  v_id bigint;
begin
  if v_user is null then
    raise exception 'sign in to report a bug or suggest an improvement' using errcode = '42501';
  end if;
  if p_kind not in ('bug', 'improvement') then
    raise exception 'choose Bug or Improvement' using errcode = '22023';
  end if;
  if char_length(v_title) < 5 or char_length(v_title) > 140 then
    raise exception 'the title needs 5 to 140 characters' using errcode = '22023';
  end if;
  if char_length(v_notes) < 10 or char_length(v_notes) > 12000 then
    raise exception 'the notes need 10 to 12000 characters' using errcode = '22023';
  end if;
  -- One row per user in the ledger is locked implicitly by the count + insert inside this transaction;
  -- a burst can slip one over the line under heavy concurrency, which is acceptable for a rate limit.
  select count(*) into v_recent from public.feedback_submissions s where s.user_id = v_user and s.created_at > now() - interval '1 hour';
  if v_recent >= 10 then
    raise exception 'you have sent ten reports in the last hour; please wait a while before sending more' using errcode = 'P0001';
  end if;
  select p.display_name into v_name from public.profiles p where p.user_id = v_user;
  v_name := coalesce(nullif(btrim(v_name), ''), 'A player');
  insert into public.feedback_issues (kind, title, notes, priority, status, reported_by)
    values (p_kind, v_title, v_notes, 'medium', 'reported', left(v_name, 60))
    returning id into v_id;
  insert into public.feedback_submissions (issue_id, user_id) values (v_id, v_user);
  insert into public.feedback_subscriptions (user_id, issue_id) values (v_user, v_id) on conflict do nothing;
  return v_id;
end;
$$;
revoke all on function public.submit_feedback(text, text, text) from public;
grant execute on function public.submit_feedback(text, text, text) to authenticated;

-- ---------------------------------------------------------------------------------------------
-- follow_feedback: follow or unfollow; a duplicate is followed through its canonical issue.
-- ---------------------------------------------------------------------------------------------
create or replace function public.follow_feedback(p_issue_id bigint, p_follow boolean)
returns void
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_user uuid := auth.uid();
  v_canonical bigint;
begin
  if v_user is null then
    raise exception 'sign in to follow an issue' using errcode = '42501';
  end if;
  v_canonical := public.feedback_canonical(p_issue_id);
  if p_follow then
    insert into public.feedback_subscriptions (user_id, issue_id) values (v_user, v_canonical) on conflict do nothing;
  else
    delete from public.feedback_subscriptions where user_id = v_user and issue_id in (p_issue_id, v_canonical);
  end if;
end;
$$;
revoke all on function public.follow_feedback(bigint, boolean) from public;
grant execute on function public.follow_feedback(bigint, boolean) to authenticated;

-- ---------------------------------------------------------------------------------------------
-- review_feedback: a maintainer edits title, notes, kind, priority, status and the linked release.
-- Stale edits are rejected (p_expected_updated_at must match). implemented/confirmed need a
-- published release. Parameters with defaults must trail, so p_expected_updated_at comes before
-- p_release_id; callers pass named arguments.
-- ---------------------------------------------------------------------------------------------
create or replace function public.review_feedback(
  p_issue_id bigint, p_title text, p_notes text, p_priority text, p_status text, p_kind text,
  p_expected_updated_at timestamptz, p_release_id uuid default null
)
returns void
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_row public.feedback_issues%rowtype;
  v_title text := btrim(coalesce(p_title, ''));
  v_notes text := btrim(coalesce(p_notes, ''));
  v_published timestamptz;
begin
  perform public.require_feedback_maintainer();
  select * into v_row from public.feedback_issues where id = p_issue_id for update;
  if not found then raise exception 'feedback issue % not found', p_issue_id using errcode = 'P0002'; end if;
  if p_expected_updated_at is null or v_row.updated_at is distinct from p_expected_updated_at then
    raise exception 'This issue changed since you opened it. Reload and review it again.' using errcode = '40001';
  end if;
  if p_kind not in ('bug', 'improvement') then raise exception 'choose Bug or Improvement' using errcode = '22023'; end if;
  if p_priority not in ('high', 'medium', 'low') then raise exception 'choose a priority' using errcode = '22023'; end if;
  if p_status not in ('reported', 'reviewed', 'working_on', 'implemented', 'confirmed') then raise exception 'choose a status' using errcode = '22023'; end if;
  if char_length(v_title) < 5 or char_length(v_title) > 140 then raise exception 'the title needs 5 to 140 characters' using errcode = '22023'; end if;
  if char_length(v_notes) < 10 or char_length(v_notes) > 12000 then raise exception 'the notes need 10 to 12000 characters' using errcode = '22023'; end if;
  if p_release_id is not null then
    select published_at into v_published from public.feedback_releases where id = p_release_id;
    if not found then raise exception 'release not found' using errcode = 'P0002'; end if;
  end if;
  if p_status in ('implemented', 'confirmed') then
    if p_release_id is null then
      raise exception 'Implemented and Confirmed need the release that shipped the change.' using errcode = 'P0001';
    end if;
    if v_published is null then
      raise exception 'That release is not published yet. Publish it first, or keep the issue at Working on.' using errcode = 'P0001';
    end if;
  end if;
  update public.feedback_issues
     set kind = p_kind, title = v_title, notes = v_notes, priority = p_priority, status = p_status, release_id = p_release_id
   where id = p_issue_id;
end;
$$;
revoke all on function public.review_feedback(bigint, text, text, text, text, text, timestamptz, uuid) from public;
grant execute on function public.review_feedback(bigint, text, text, text, text, text, timestamptz, uuid) to authenticated;

-- ---------------------------------------------------------------------------------------------
-- merge_feedback: mark an issue as a duplicate of another (resolved to that issue's canonical),
-- moving its followers across. Nobody is told anything was fixed; the duplicate stays visible with
-- its notes and a link. Locks both rows in id order; refuses self, cycles and re-merging.
-- ---------------------------------------------------------------------------------------------
create or replace function public.merge_feedback(p_issue_id bigint, p_target_id bigint)
returns void
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_canonical bigint;
  v_dup bigint;
begin
  perform public.require_feedback_maintainer();
  if p_issue_id = p_target_id then raise exception 'an issue cannot be a duplicate of itself' using errcode = 'P0001'; end if;
  v_canonical := public.feedback_canonical(p_target_id);
  if v_canonical = p_issue_id then
    raise exception 'that would make issues #% and #% duplicates of each other', p_issue_id, p_target_id using errcode = 'P0001';
  end if;
  -- Lock in a stable order so two maintainers merging opposite ways cannot deadlock.
  perform id from public.feedback_issues where id in (p_issue_id, v_canonical) order by id for update;
  select duplicate_of into v_dup from public.feedback_issues where id = p_issue_id;
  if not found then raise exception 'feedback issue % not found', p_issue_id using errcode = 'P0002'; end if;
  if v_dup is not null then
    raise exception 'issue #% is already recorded as a duplicate of #%', p_issue_id, v_dup using errcode = 'P0001';
  end if;
  -- Anything already pointing at the merged issue now points at the canonical one too.
  update public.feedback_issues set duplicate_of = v_canonical where duplicate_of = p_issue_id;
  update public.feedback_issues set duplicate_of = v_canonical where id = p_issue_id;
  insert into public.feedback_subscriptions (user_id, issue_id)
    select s.user_id, v_canonical from public.feedback_subscriptions s where s.issue_id = p_issue_id
    on conflict do nothing;
  delete from public.feedback_subscriptions where issue_id = p_issue_id;
end;
$$;
revoke all on function public.merge_feedback(bigint, bigint) from public;
grant execute on function public.merge_feedback(bigint, bigint) to authenticated;

-- ---------------------------------------------------------------------------------------------
-- publish_feedback_release: a maintainer (or the service role) publishes a draft. Linked issues at
-- Working on become Implemented; everyone following a linked Implemented/Confirmed issue is told
-- once per issue and release (dedupe_key). Reported/Reviewed issues are left alone. Re-running is
-- harmless: nothing is re-sent, nothing re-advanced.
-- ---------------------------------------------------------------------------------------------
create or replace function public.publish_feedback_release(p_release_id uuid)
returns void
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_rel public.feedback_releases%rowtype;
begin
  if not public.is_service_role() then
    perform public.require_feedback_maintainer();
  end if;
  select * into v_rel from public.feedback_releases where id = p_release_id for update;
  if not found then raise exception 'release not found' using errcode = 'P0002'; end if;
  if v_rel.published_at is null then
    update public.feedback_releases set published_at = now() where id = p_release_id;
  end if;
  update public.feedback_issues set status = 'implemented'
   where release_id = p_release_id and status = 'working_on';
  insert into public.app_notifications (user_id, kind, title, body, href, dedupe_key)
    select s.user_id, 'feedback_release',
           left(format('#%s is in release %s', i.id, v_rel.version), 140),
           left(format('%s — now %s. %s', i.title, case i.status when 'confirmed' then 'confirmed' else 'implemented' end, v_rel.title), 2000),
           format('/feedback/%s', i.id),
           format('release:%s:issue:%s:user:%s', p_release_id, i.id, s.user_id)
      from public.feedback_issues i
      join public.feedback_subscriptions s on s.issue_id = i.id
     where i.release_id = p_release_id and i.status in ('implemented', 'confirmed')
    on conflict (dedupe_key) do nothing;
end;
$$;
revoke all on function public.publish_feedback_release(uuid) from public;
grant execute on function public.publish_feedback_release(uuid) to authenticated, service_role;

-- ---------------------------------------------------------------------------------------------
-- mark_notification_read: the owner marks one notification read; anyone else is refused.
-- ---------------------------------------------------------------------------------------------
create or replace function public.mark_notification_read(p_id uuid)
returns void
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_user uuid := auth.uid();
  v_count int;
begin
  if v_user is null then raise exception 'sign in first' using errcode = '42501'; end if;
  update public.app_notifications set read_at = coalesce(read_at, now()) where id = p_id and user_id = v_user;
  get diagnostics v_count = row_count;
  if v_count = 0 then raise exception 'notification not found' using errcode = 'P0002'; end if;
end;
$$;
revoke all on function public.mark_notification_read(uuid) from public;
grant execute on function public.mark_notification_read(uuid) to authenticated;
