-- #229 / #95 Engine of Chaos custody. A captured Hero can be locked in a Chaos Dwarf Engine through
-- an ordinary two-party captive proposal: the victim's player agrees the exact confiscation (the
-- Hero's equipment passes to the Chaos Dwarf stash) and the Hero stays captured while his case moves
-- to a new 'held' state. Imprisonment is not an outcome, so ransom, exchange and sale stay off until
-- the placement is reversed. Custody lives in engine_prisoners: named prisoners linked to their case
-- and report, anonymous prisoners from the holder's own exploration report (Straggler = one,
-- Prisoners = D3, counted per report across every Engine). Places are counted against the Engine's
-- six (a Large captive takes two) under the inventory locks of 101. Rescue, dispatch and reward are
-- follow-ons; reversing a placement frees the place and returns the kit through the 090 snapshot.
--
-- 101 interaction fixed here: the 090 reversal deleted and re-inserted every item row of both
-- warbands, which would retire and recreate a Chaos Dwarf Engine's physical identities (101 keys
-- them to the stock item row). Items are now restored in place, so unchanged rows keep their ids.

alter table public.captive_cases drop constraint captive_cases_state_check;
alter table public.captive_cases add constraint captive_cases_state_check check (state in ('unassigned', 'open', 'held', 'resolved', 'withdrawn'));

-- ---------------------------------------------------------------------------------------------
-- Native profile traits (generated by scripts/generate-capture-traits.mjs from the catalogue:
-- unitIsLarge / unitRules.isAnimal and the Hired Sword / Dramatis Personae rule headings). Keys are
-- unit ids or hired:<hired_sword_rules_id>. Private data for security-definer checks; the row's own
-- is_large is always OR-ed in so a promoted or house-ruled Large warrior is never undercharged.
-- ---------------------------------------------------------------------------------------------
create table public.capture_unit_traits (
  unit_key text primary key,
  large boolean not null default false,
  animal boolean not null default false
);
comment on table public.capture_unit_traits is 'Generated native Large/animal classification of catalogue profiles (scripts/generate-capture-traits.mjs). Regenerate and replace, never edit by hand.';
alter table public.capture_unit_traits enable row level security;
insert into public.capture_unit_traits (unit_key, large, animal) values
  ('acolytes',false,false),
  ('amazons_lustria_amazon_warrior',false,false),
  ('amazons_lustria_eagle_warrior',false,false),
  ('amazons_lustria_jaguar_warrior',false,false),
  ('amazons_lustria_piranha_warrior',false,false),
  ('amazons_lustria_serpent_priestess',false,false),
  ('amazons_mordheim_amazon_warrior',false,false),
  ('amazons_mordheim_champion',false,false),
  ('amazons_mordheim_priestess',false,false),
  ('amazons_mordheim_scout',false,false),
  ('amazons_mordheim_totem_warrior',false,false),
  ('apprentices',false,false),
  ('arabian_tomb_raiders_bedouin',false,false),
  ('arabian_tomb_raiders_champion',false,false),
  ('arabian_tomb_raiders_mystic',false,false),
  ('arabian_tomb_raiders_nomad_warrior',false,false),
  ('arabian_tomb_raiders_sheikh',false,false),
  ('arabian_tomb_raiders_slave',false,false),
  ('archers',false,false),
  ('averlander_bergjaeger',false,false),
  ('averlander_bergjaeger__priest_of_morr',false,false),
  ('averlander_captain',false,false),
  ('averlander_halfling_scouts',false,false),
  ('averlander_marksmen',false,false),
  ('averlander_mountainguard',false,false),
  ('averlander_sergeant',false,false),
  ('averlander_sergeant__priest_of_morr',false,false),
  ('averlander_youngblood',false,false),
  ('averlander_youngblood__priest_of_morr',false,false),
  ('bandit_leader',false,false),
  ('battle_monks_dragon_monks',false,false),
  ('battle_monks_emissary',false,false),
  ('battle_monks_officer',false,false),
  ('battle_monks_raging_peasants',false,false),
  ('battle_monks_soldiers',false,false),
  ('battle_monks_warrior_monks',false,false),
  ('beastmen_bestigors',false,false),
  ('beastmen_centigors',false,false),
  ('beastmen_chieftain',false,false),
  ('beastmen_gor',false,false),
  ('beastmen_minotaur',true,false),
  ('beastmen_shaman',false,false),
  ('beastmen_ungor',false,false),
  ('beastmen_warhounds_of_chaos',false,true),
  ('bigsnotz',false,false),
  ('black_dwarfs_bull_centaur',true,false),
  ('black_dwarfs_chaos_dwarfs',false,false),
  ('black_dwarfs_gaolers',false,false),
  ('black_dwarfs_informers',false,false),
  ('black_dwarfs_sorcerer',false,false),
  ('black_orcs_black_orc',false,false),
  ('black_orcs_black_orc_boss',false,false),
  ('black_orcs_orc_boy',false,false),
  ('black_orcs_orc_nutta',false,false),
  ('black_orcs_orc_shoota',false,false),
  ('black_orcs_troll',true,false),
  ('black_orcs_youngun',false,false),
  ('bowmen',false,false),
  ('bretonnian_battle_pilgrims',false,false),
  ('bretonnian_bowmen',false,false),
  ('bretonnian_damsel',false,false),
  ('bretonnian_knight_errant',false,false),
  ('bretonnian_knights_bowmen',false,false),
  ('bretonnian_knights_knight_errant',false,false),
  ('bretonnian_knights_men_at_arms',false,false),
  ('bretonnian_knights_questing_knight',false,false),
  ('bretonnian_knights_squire',false,false),
  ('bretonnian_questing_knight',false,false),
  ('bretonnian_squires',false,false),
  ('bullied_goblin',false,false),
  ('carnival_of_chaos_brethren',false,false),
  ('carnival_of_chaos_brutes',false,false),
  ('carnival_of_chaos_master',false,false),
  ('carnival_of_chaos_nurglings',false,false),
  ('carnival_of_chaos_plague_bearers',false,false),
  ('carnival_of_chaos_plague_cart',false,false),
  ('carnival_of_chaos_tainted_ones',false,false),
  ('champions',false,false),
  ('clanrats',false,false),
  ('cleric',false,false),
  ('companion_filly',false,true),
  ('companions',false,false),
  ('court_of_pleasures_beastmen',false,false),
  ('court_of_pleasures_chaos_hounds',false,true),
  ('court_of_pleasures_cultists',false,false),
  ('court_of_pleasures_danseuse',false,false),
  ('court_of_pleasures_devout',false,false),
  ('court_of_pleasures_flesh_merchant',false,false),
  ('court_of_pleasures_priest_of_obscene',false,false),
  ('court_of_pleasures_whipmaster',false,false),
  ('court_of_pleasures_wretches',false,false),
  ('crusaders',false,false),
  ('cult_of_the_possessed_beastmen',false,false),
  ('cult_of_the_possessed_brethren',false,false),
  ('cult_of_the_possessed_darksouls',false,false),
  ('cult_of_the_possessed_magister',false,false),
  ('cult_of_the_possessed_mutants',false,false),
  ('cult_of_the_possessed_the_possessed',false,false),
  ('cursed_cavalcade_aristocrat',false,false),
  ('cursed_cavalcade_captured_thrall',false,false),
  ('cursed_cavalcade_companions',false,false),
  ('cursed_cavalcade_cursed_piper',false,false),
  ('cursed_cavalcade_fighting_ape',false,true),
  ('cursed_cavalcade_great_bear',true,true),
  ('cursed_cavalcade_thrall',false,false),
  ('cursed_cavalcade_twisted_scholar',false,false),
  ('cursed_cavalcade_wild_beasts',false,true),
  ('dame_of_the_mare',false,false),
  ('dark_elves_beastmaster',false,false),
  ('dark_elves_cold_one_beasthound',false,true),
  ('dark_elves_corsair',false,false),
  ('dark_elves_fellblade',false,false),
  ('dark_elves_high_born',false,false),
  ('dark_elves_shade',false,false),
  ('dark_elves_sorceress',false,false),
  ('deepwood_scouts',false,false),
  ('domnu',false,false),
  ('dreamwalkers_andanti',false,false),
  ('dreamwalkers_black_guards_of_morr',false,false),
  ('dreamwalkers_deaths_heads_of_ostermark',false,false),
  ('dreamwalkers_dreamer',false,false),
  ('dreamwalkers_morr_worshwishpers_henchmen',false,false),
  ('dreamwalkers_priest_of_morr',false,false),
  ('druchii_beastmaster',false,false),
  ('druchii_corsairs',false,false),
  ('druchii_lordlings',false,false),
  ('druchii_noble',false,false),
  ('druchii_shades_henchmen',false,false),
  ('druchii_slavehounds',false,true),
  ('druchii_sorceress',false,false),
  ('druchii_witch_elves_henchmen',false,false),
  ('dwarf_rangers_apprentice_runesmith',false,false),
  ('dwarf_rangers_beardling',false,false),
  ('dwarf_rangers_dwarf_clansman',false,false),
  ('dwarf_rangers_dwarf_crossbowman',false,false),
  ('dwarf_rangers_dwarf_longbeard',false,false),
  ('dwarf_rangers_runesmith',false,false),
  ('dwarf_rangers_troll_slayer',false,false),
  ('dwarf_slayer_cult_axe_hurlers',false,false),
  ('dwarf_slayer_cult_doomseeker_hero',false,false),
  ('dwarf_slayer_cult_giant_slayer',false,false),
  ('dwarf_slayer_cult_rememberer_hero',false,false),
  ('dwarf_slayer_cult_stubbles',false,false),
  ('dwarf_slayer_cult_troll_slayers',false,false),
  ('dwarf_treasure_hunters_beardlings',false,false),
  ('dwarf_treasure_hunters_clansmen',false,false),
  ('dwarf_treasure_hunters_engineer',false,false),
  ('dwarf_treasure_hunters_noble',false,false),
  ('dwarf_treasure_hunters_thunderers',false,false),
  ('dwarf_treasure_hunters_troll_slayers',false,false),
  ('esquiresses',false,false),
  ('forest_goblins_brave',false,false),
  ('forest_goblins_chieftain',false,false),
  ('forest_goblins_forest_goblin',false,false),
  ('forest_goblins_gigantic_spider',true,true),
  ('forest_goblins_red_toof_goblin',false,false),
  ('forest_goblins_shaman',false,false),
  ('forest_goblins_slugga',false,false),
  ('forest_mage',false,false),
  ('gallant',false,false),
  ('ghouls',false,false),
  ('giant_bats',true,true),
  ('giant_rats',false,true),
  ('glade_guard',false,false),
  ('grave_robbers_grave_robber',false,false),
  ('grave_robbers_graver',false,false),
  ('grave_robbers_junior_medic',false,false),
  ('grave_robbers_lookout',false,false),
  ('grave_robbers_thugs',false,false),
  ('grunts',false,false),
  ('gunnery_school_of_nuln_instructor',false,false),
  ('gunnery_school_of_nuln_marksman',false,false),
  ('gunnery_school_of_nuln_pistolier',false,false),
  ('gunnery_school_of_nuln_senior_gunnery_officer',false,false),
  ('gunnery_school_of_nuln_senior_student',false,false),
  ('gunnery_school_of_nuln_sons_of_the_guns',false,false),
  ('gunnery_school_of_nuln_underclassman',false,false),
  ('halflings_cook',false,false),
  ('halflings_elder',false,false),
  ('halflings_piggies',false,true),
  ('halflings_scouts',false,false),
  ('halflings_thief_hero',false,false),
  ('halflings_village_ogre_henchman',true,false),
  ('halflings_warriors',false,false),
  ('halflings_youths',false,false),
  ('hired:abdul_alhazred_the_mad_sorcerer',false,false),
  ('hired:aenur_the_sword_of_twilight',false,false),
  ('hired:aksho_akhash_the_vile_dreadwing_lord_of_the_carrion_throne',false,false),
  ('hired:arabian_merchant',false,false),
  ('hired:bard',false,false),
  ('hired:beast_hunter',false,false),
  ('hired:beggar',false,false),
  ('hired:belandysh_condemned_champion_of_chen',false,false),
  ('hired:bertha_bestraufrung_high_matriarch_of_the_sisterhood',false,false),
  ('hired:big_game_hunter',false,false),
  ('hired:black_orc_overseer',false,false),
  ('hired:bone_goliath',true,false),
  ('hired:bounty_hunter',false,false),
  ('hired:busty_gwen',false,false),
  ('hired:cathayan_merchant',false,false),
  ('hired:chameleon_skink',false,false),
  ('hired:chaos_centaur',false,false),
  ('hired:chaos_fury',false,false),
  ('hired:clan_skryre_rat_ogre',true,false),
  ('hired:coachman',false,false),
  ('hired:countess_marianna_chevaux_vampire_assassin',false,false),
  ('hired:crow_master_the',false,false),
  ('hired:cursed_hillman',false,false),
  ('hired:dark_elf_assassin',false,false),
  ('hired:dark_emissary',false,false),
  ('hired:dark_mage',false,false),
  ('hired:dijin_katal_the_renegade_assassin',false,false),
  ('hired:drenok_johansen_wielder_of_the_great_axe',false,false),
  ('hired:duellist',false,false),
  ('hired:dwarf_pathfinder',false,false),
  ('hired:dwarf_slayer_pirate',false,false),
  ('hired:dwarf_treasure_hunter',false,false),
  ('hired:dwarf_troll_slayer',false,false),
  ('hired:elf_mage',false,false),
  ('hired:elf_ranger',false,false),
  ('hired:emissary_of_chaos',false,false),
  ('hired:estalian_diestro',false,false),
  ('hired:freelancer',false,false),
  ('hired:gaoler',false,false),
  ('hired:goblin_lantern_bearer',false,false),
  ('hired:grand_master_ippan_shu',false,false),
  ('hired:grave_robber',false,false),
  ('hired:gravesman',false,false),
  ('hired:halfling_knight',true,false),
  ('hired:halfling_scout',false,false),
  ('hired:halfling_thief',false,false),
  ('hired:heinrich_altdorf_schmidt',false,false),
  ('hired:highwayman',false,false),
  ('hired:hobgoblin_scout',false,false),
  ('hired:human_scout',false,false),
  ('hired:imperial_assassin',false,false),
  ('hired:imperial_tactician',false,false),
  ('hired:innominatus_the_tilean_gladiator',false,false),
  ('hired:johann_the_knife',false,false),
  ('hired:khar_mel_the_djinn',false,false),
  ('hired:kislev_ranger',false,false),
  ('hired:knight_of_the_white_wolf',false,false),
  ('hired:luthor_the_looter',false,false),
  ('hired:luthor_wolfenbaum',false,false),
  ('hired:maglah_khan_s_horde',false,false),
  ('hired:maximilian_the_mad',false,false),
  ('hired:mule_skinner',false,false),
  ('hired:nicodemus_the_cursed_pilgrim',false,false),
  ('hired:ninja',false,false),
  ('hired:ninja_gnoblar',false,false),
  ('hired:nomad_scout',false,false),
  ('hired:norse_shaman',false,false),
  ('hired:ogre_bodyguard',true,false),
  ('hired:ogre_slave_master',true,false),
  ('hired:old_prospector',false,false),
  ('hired:pathfinder',false,false),
  ('hired:penthesilea_mark_of_the_serpent',false,false),
  ('hired:pit_fighter',false,false),
  ('hired:priest_of_morr',false,false),
  ('hired:pyromaniac',false,false),
  ('hired:roadwarden',false,false),
  ('hired:runesmith_journeyman',false,false),
  ('hired:shadow_warrior',false,false),
  ('hired:sigmund_spindle_the_harvester_of_flesh',false,false),
  ('hired:slaver',false,false),
  ('hired:snake_charmer',false,true),
  ('hired:swashbuckler',false,false),
  ('hired:swordsmith',false,false),
  ('hired:the_dark_jester_in_mordheim',false,false),
  ('hired:the_fallen_sister',false,false),
  ('hired:the_foole',false,false),
  ('hired:the_headless_horseman',false,false),
  ('hired:thief',false,false),
  ('hired:tilean_marksman',false,false),
  ('hired:tomb_robber',false,false),
  ('hired:truthsayer',false,false),
  ('hired:ulli_and_marquand',false,false),
  ('hired:ungor_trapper',false,false),
  ('hired:veskit_high_executioner_of_clan_eshin',false,false),
  ('hired:warlock',false,false),
  ('hired:warrior_priest_of_sigmar',false,false),
  ('hired:weaponsmith',false,false),
  ('hired:william_schakestange_master_bard',false,false),
  ('hired:witch',false,false),
  ('hired:witch_hunter',false,false),
  ('hired:wolf_priest_of_ulric',false,false),
  ('hired:wood_elf_hunter',false,false),
  ('hochland_bandits_bandit_prince',false,false),
  ('hochland_bandits_blackheart',false,false),
  ('hochland_bandits_duelist',false,false),
  ('hochland_bandits_footpad',false,false),
  ('hochland_bandits_gutterscum',false,false),
  ('hochland_bandits_huckster',false,false),
  ('hochland_bandits_looter',false,false),
  ('hochland_bandits_poacher',false,false),
  ('hochland_bandits_thug',false,false),
  ('horned_hunters_drunken_gang',false,false),
  ('horned_hunters_horned_hunter',false,false),
  ('horned_hunters_initiate',false,false),
  ('horned_hunters_priest_of_taal',false,false),
  ('horned_hunters_warhound',false,true),
  ('horned_hunters_zealot',false,false),
  ('hounds',false,true),
  ('hunt_master',false,false),
  ('huntsman',false,false),
  ('imperial_outriders_chasseur',false,false),
  ('imperial_outriders_groom',false,false),
  ('imperial_outriders_hussar',false,false),
  ('imperial_outriders_knight',false,false),
  ('imperial_outriders_outrider',false,false),
  ('imperial_outriders_scout',false,false),
  ('kislevites_bear_tamer',false,false),
  ('kislevites_cossacks',false,false),
  ('kislevites_druzhina_captain',false,false),
  ('kislevites_esaul',false,false),
  ('kislevites_streltsi',false,false),
  ('kislevites_trained_bear',true,true),
  ('kislevites_warriors',false,false),
  ('kislevites_youths',false,false),
  ('lizardmen_kroxigor',true,true),
  ('lizardmen_saurus_brave',false,false),
  ('lizardmen_saurus_totem_warrior',false,false),
  ('lizardmen_skink_brave',false,false),
  ('lizardmen_skink_great_crest',false,false),
  ('lizardmen_skink_priest',false,false),
  ('lustrian_reavers_barbary_monkey',false,false),
  ('lustrian_reavers_beastmaster',false,false),
  ('lustrian_reavers_conqueror',false,false),
  ('lustrian_reavers_estalian_warhound',false,false),
  ('lustrian_reavers_jungle_shadow',false,false),
  ('lustrian_reavers_prospects',false,false),
  ('lustrian_reavers_saurus_slayer',false,false),
  ('lustrian_reavers_tilean_hunting_hawk',false,false),
  ('lustrian_reavers_trapmaster',false,false),
  ('mages',false,false),
  ('magus',false,false),
  ('maneaters_bulls',true,false),
  ('maneaters_captain',true,false),
  ('maneaters_half_growns',false,false),
  ('maneaters_mountain_guide',true,false),
  ('maneaters_sabretusks',false,true),
  ('maneaters_youngbloods',false,false),
  ('marauders_champions',false,false),
  ('marauders_chaos_marauders',false,false),
  ('marauders_chieftain',false,false),
  ('marauders_condemned',false,false),
  ('marauders_seer',false,false),
  ('marauders_spawn_of_chaos',true,false),
  ('marauders_warhounds_of_chaos',false,true),
  ('marksmen',false,false),
  ('masters_of_horror_flesh_construct',false,false),
  ('masters_of_horror_hunchbacks',false,false),
  ('masters_of_horror_mad_scientist',false,false),
  ('masters_of_horror_the_bitten',false,false),
  ('masters_of_horror_thrall',false,false),
  ('masters_of_horror_wolfman',false,false),
  ('masters_of_horror_zombies',false,false),
  ('mazzalupo_black_sheep',false,true),
  ('mazzalupo_churl',false,false),
  ('mazzalupo_fallen_noble',false,false),
  ('mazzalupo_master_of_finances',false,false),
  ('mazzalupo_sheepherders',false,false),
  ('mazzalupo_squire',false,false),
  ('mazzalupo_wandering_knight',false,false),
  ('mercenaries_marienburg_captain',false,false),
  ('mercenaries_marienburg_champions',false,false),
  ('mercenaries_marienburg_champions__priest_of_morr',false,false),
  ('mercenaries_marienburg_marksmen',false,false),
  ('mercenaries_marienburg_swordsmen',false,false),
  ('mercenaries_marienburg_warriors',false,false),
  ('mercenaries_marienburg_youngbloods',false,false),
  ('mercenaries_marienburg_youngbloods__priest_of_morr',false,false),
  ('mercenaries_middenheim_captain',false,false),
  ('mercenaries_middenheim_champions',false,false),
  ('mercenaries_middenheim_champions__priest_of_morr',false,false),
  ('mercenaries_middenheim_champions__wolf_priest_of_ulric',false,false),
  ('mercenaries_middenheim_marksmen',false,false),
  ('mercenaries_middenheim_swordsmen',false,false),
  ('mercenaries_middenheim_warriors',false,false),
  ('mercenaries_middenheim_youngbloods',false,false),
  ('mercenaries_middenheim_youngbloods__priest_of_morr',false,false),
  ('mercenaries_ostermark_captain',false,false),
  ('mercenaries_ostermark_champions',false,false),
  ('mercenaries_ostermark_champions__priest_of_morr',false,false),
  ('mercenaries_ostermark_marksmen',false,false),
  ('mercenaries_ostermark_swordsmen',false,false),
  ('mercenaries_ostermark_warriors',false,false),
  ('mercenaries_ostermark_youngbloods',false,false),
  ('mercenaries_ostermark_youngbloods__priest_of_morr',false,false),
  ('mercenaries_reikland_captain',false,false),
  ('mercenaries_reikland_champions',false,false),
  ('mercenaries_reikland_champions__priest_of_morr',false,false),
  ('mercenaries_reikland_marksmen',false,false),
  ('mercenaries_reikland_swordsmen',false,false),
  ('mercenaries_reikland_warriors',false,false),
  ('mercenaries_reikland_youngbloods',false,false),
  ('mercenaries_reikland_youngbloods__priest_of_morr',false,false),
  ('merchant_apprentice',false,false),
  ('merchant_blackguards',false,false),
  ('merchant_knights_vanguard',false,false),
  ('merchant_magician',false,false),
  ('merchant_marksmen',false,false),
  ('merchant_merchant',false,false),
  ('merchant_sell_swords',false,false),
  ('merchant_trade_wagon',false,false),
  ('mootlanders_halfling_thief',false,false),
  ('mootlanders_master_chef',false,false),
  ('mootlanders_moot_elder',false,false),
  ('mootlanders_scout',false,false),
  ('mootlanders_warrior',false,false),
  ('necrarchs_abomination',true,false),
  ('necrarchs_acolytes',false,false),
  ('necrarchs_necrarch_vampire',false,false),
  ('necrarchs_skeletal_warriors',false,false),
  ('necrarchs_thrall',false,false),
  ('necrarchs_waifs',false,false),
  ('necrarchs_zombies',false,false),
  ('night_goblins_big_boss',false,false),
  ('night_goblins_bosses',false,false),
  ('night_goblins_cave_squigs',false,true),
  ('night_goblins_fanatics',false,false),
  ('night_goblins_shaman',false,false),
  ('night_goblins_snotling_mob',false,false),
  ('night_goblins_troll',true,false),
  ('night_goblins_warriors',false,false),
  ('night_goblins_web_boss',false,false),
  ('night_goblins_web_cave_squigs',false,true),
  ('night_goblins_web_fanatics',false,false),
  ('night_goblins_web_goonz',false,false),
  ('night_goblins_web_great_squig',true,true),
  ('night_goblins_web_shaman',false,false),
  ('night_goblins_web_snotlings',false,false),
  ('night_goblins_web_squig_herder',false,false),
  ('night_goblins_web_troll',true,false),
  ('night_goblins_web_warriors',false,false),
  ('nipponese_ashigaru',false,false),
  ('nipponese_hatamoto',false,false),
  ('nipponese_onnabushi',false,false),
  ('nipponese_retainers',false,false),
  ('nipponese_shinobi_hero',false,false),
  ('nipponese_vim_to_mage',false,false),
  ('nipponese_warrior_monks',false,false),
  ('norse_berserker',false,false),
  ('norse_bondsman',false,false),
  ('norse_hunter',false,false),
  ('norse_jarl',false,false),
  ('norse_marauder',false,false),
  ('norse_wolf',false,true),
  ('norse_wulfen',false,false),
  ('ogre_hunting_party_flingers',false,false),
  ('ogre_hunting_party_gnoblar_fighters',false,false),
  ('ogre_hunting_party_ogre_hunter',true,false),
  ('ogre_hunting_party_sabre_baiter',false,false),
  ('ogre_hunting_party_sabretusk_cubs',false,true),
  ('ogre_hunting_party_trappers',false,false),
  ('orc_mob_big_uns',false,false),
  ('orc_mob_boss',false,false),
  ('orc_mob_cave_squigs',false,true),
  ('orc_mob_goblin_warriors',false,false),
  ('orc_mob_orc_boyz',false,false),
  ('orc_mob_shaman',false,false),
  ('orc_mob_troll',true,false),
  ('ostlander_blood_brothers',false,false),
  ('ostlander_blood_brothers__priest_of_morr',false,false),
  ('ostlander_elder',false,false),
  ('ostlander_jaeger',false,false),
  ('ostlander_kin',false,false),
  ('ostlander_ogre',true,false),
  ('ostlander_priest_of_taal',false,false),
  ('ostlander_priest_of_taal__priest_of_morr',false,false),
  ('ostlander_ruffians',false,false),
  ('outlaws',false,false),
  ('outlaws_bandit_leader',false,false),
  ('outlaws_champion',false,false),
  ('outlaws_cleric',false,false),
  ('outlaws_marksman',false,false),
  ('outlaws_outlaw',false,false),
  ('outlaws_petty_thief',false,false),
  ('packmaster',false,false),
  ('paragon',false,false),
  ('petty_thieves',false,false),
  ('pilgrims',false,false),
  ('pilgrims_of_the_dark_shroud',false,false),
  ('pirates_boatswain',false,false),
  ('pirates_cabin_boy',false,false),
  ('pirates_captain',false,false),
  ('pirates_crew',false,false),
  ('pirates_gunner',false,false),
  ('pirates_ships_mate',false,false),
  ('pirates_swabbie',false,false),
  ('pit_fighters_ogre',true,false),
  ('pit_fighters_pit_fighter',false,false),
  ('pit_fighters_pit_king',false,false),
  ('pit_fighters_pit_veteran',false,false),
  ('pit_fighters_pursuer',false,false),
  ('pit_fighters_troll_slayer',false,false),
  ('priest_of_morr',false,false),
  ('rat_ogres',true,true),
  ('redeemed_knights',false,false),
  ('restless_dead_grave_guards',false,false),
  ('restless_dead_liche',false,false),
  ('restless_dead_necromancer',false,false),
  ('restless_dead_scarecrows',false,false),
  ('restless_dead_skeletons',false,false),
  ('restless_dead_variant_bone_goliath',true,false),
  ('restless_dead_variant_grave_guards',false,false),
  ('restless_dead_variant_liche',false,false),
  ('restless_dead_variant_necromancer',false,false),
  ('restless_dead_variant_skeletons',false,false),
  ('restless_dead_variant_wights',false,false),
  ('restless_dead_variant_zombies',false,false),
  ('restless_dead_wights',false,false),
  ('restless_dead_zombies',false,false),
  ('runts',false,false),
  ('seer',false,false),
  ('shadow_warriors_novice',false,false),
  ('shadow_warriors_shadow_master',false,false),
  ('shadow_warriors_shadow_walker',false,false),
  ('shadow_warriors_shadow_warrior',false,false),
  ('shadow_warriors_shadow_weaver',false,false),
  ('sisters_of_sigmar_augur',false,false),
  ('sisters_of_sigmar_matriarch',false,false),
  ('sisters_of_sigmar_novices',false,false),
  ('sisters_of_sigmar_sigmarite_sister',false,false),
  ('sisters_of_sigmar_sister_superior',false,false),
  ('skaven_assassin_adept',false,false),
  ('skaven_black_skaven',false,false),
  ('skaven_eshin_sorcerer',false,false),
  ('skaven_giant_rats',false,true),
  ('skaven_night_runners',false,false),
  ('skaven_pestilens_giant_rat',false,true),
  ('skaven_pestilens_monk_initiate',false,false),
  ('skaven_pestilens_plague_monk',false,false),
  ('skaven_pestilens_plague_novice',false,false),
  ('skaven_pestilens_plague_priest',false,false),
  ('skaven_pestilens_rat_ogre',true,true),
  ('skaven_pestilens_sorcerer',false,false),
  ('skaven_rat_ogre',true,true),
  ('skaven_verminkin',false,false),
  ('slayers',false,false),
  ('snotling_mobs',false,false),
  ('snotling_scouts',false,false),
  ('snotling_shaman',false,false),
  ('snotling_shoota_team',false,false),
  ('snotling_wheelo',false,false),
  ('sons_of_hashut_apprentice_sorcerer',false,false),
  ('sons_of_hashut_blunderbuss_chaos_dwarfs',false,false),
  ('sons_of_hashut_bull_centaur',true,false),
  ('sons_of_hashut_chaos_dwarf_champions',false,false),
  ('sons_of_hashut_chaos_dwarf_warriors',false,false),
  ('sons_of_hashut_hobgoblins',false,false),
  ('stormvermin',false,false),
  ('strigany',false,false),
  ('strigoi_vampire',false,false),
  ('templars',false,false),
  ('tileans_miragleans_captain',false,false),
  ('tileans_miragleans_champion',false,false),
  ('tileans_miragleans_duellist',false,false),
  ('tileans_miragleans_marksman',false,false),
  ('tileans_miragleans_warrior',false,false),
  ('tileans_miragleans_youngblood',false,false),
  ('tileans_remasens_captain',false,false),
  ('tileans_remasens_champion',false,false),
  ('tileans_remasens_duellist',false,false),
  ('tileans_remasens_marksman',false,false),
  ('tileans_remasens_warrior',false,false),
  ('tileans_remasens_youngblood',false,false),
  ('tileans_trantios_captain',false,false),
  ('tileans_trantios_champion',false,false),
  ('tileans_trantios_duellist',false,false),
  ('tileans_trantios_marksman',false,false),
  ('tileans_trantios_warrior',false,false),
  ('tileans_trantios_youngblood',false,false),
  ('tomb_guardians_acolyte',false,false),
  ('tomb_guardians_liche_priest',false,false),
  ('tomb_guardians_skeleton_warrior',false,false),
  ('tomb_guardians_tomb_guard',false,false),
  ('tomb_guardians_tomb_lord',false,false),
  ('tomb_guardians_tomb_scorpion',false,true),
  ('undead_dire_wolves',false,true),
  ('undead_dregs',false,false),
  ('undead_ghouls',false,false),
  ('undead_necromancer',false,false),
  ('undead_vampire',false,false),
  ('undead_zombies',false,false),
  ('untrained',false,false),
  ('vampire_hunter',false,false),
  ('villagers',false,false),
  ('warrior_priest',false,false),
  ('waywatcher',false,false),
  ('witch_hunters_captain',false,false),
  ('witch_hunters_flagellants',false,false),
  ('witch_hunters_war_hounds',false,true),
  ('witch_hunters_warrior_priest',false,false),
  ('witch_hunters_witch_hunters',false,false),
  ('witch_hunters_zealots',false,false),
  ('wolf_rats',false,true),
  ('wolfhounds',false,true);

create function public.capture_unit_key(p_unit_type_rules_id text, p_is_hired_sword boolean, p_hired_sword_rules_id text) returns text language sql immutable as $$
  select case when coalesce(p_is_hired_sword, false) and coalesce(p_hired_sword_rules_id, '') <> '' then 'hired:' || p_hired_sword_rules_id else p_unit_type_rules_id end;
$$;
create function public.capture_unit_large(p_unit_key text, p_row_large boolean) returns boolean language sql stable security definer set search_path = '' as $$
  select coalesce(p_row_large, false) or exists (select 1 from public.capture_unit_traits t where t.unit_key = p_unit_key and t.large);
$$;
create function public.capture_unit_animal(p_unit_key text) returns boolean language sql stable security definer set search_path = '' as $$
  select exists (select 1 from public.capture_unit_traits t where t.unit_key = p_unit_key and t.animal);
$$;
revoke all on function public.capture_unit_key(text, boolean, text) from public;
revoke all on function public.capture_unit_large(text, boolean) from public;
revoke all on function public.capture_unit_animal(text) from public;

-- ---------------------------------------------------------------------------------------------
-- Custody record.
-- ---------------------------------------------------------------------------------------------
create table public.engine_prisoners (
  id uuid primary key default gen_random_uuid(),
  engine_id uuid not null references public.engine_of_chaos_units (id) on delete cascade,
  holder_warband_id uuid not null references public.warbands (id) on delete cascade,
  case_id uuid references public.captive_cases (id) on delete cascade,
  exploration_report_id uuid references public.match_reports (id) on delete cascade,
  victim_warband_id uuid references public.warbands (id) on delete set null,
  name text not null check (char_length(btrim(name)) between 1 and 80),
  large boolean not null default false,
  places integer not null constraint engine_prisoners_places_check check (places = case when large then 2 else 1 end),
  -- Named: the Hero row and his original item rows as they stood before confiscation, with the
  -- case's report identity. Anonymous: the report identity, its exploration location and the D3.
  snapshot jsonb not null default '{}'::jsonb,
  -- The exact item rows moved to the holder's stash (the accepted proposal's captor-side changes).
  confiscated jsonb not null default '[]'::jsonb,
  state text not null default 'held' check (state in ('held', 'reversed', 'freed', 'dispatched')),
  proposal_id uuid references public.captive_proposals (id) on delete set null,
  placed_by uuid references auth.users (id),
  placed_at timestamptz not null default now(),
  released_at timestamptz,
  release_reason text not null default '',
  history jsonb not null default '[]'::jsonb,
  constraint engine_prisoners_source_check check ((case_id is not null) <> (exploration_report_id is not null))
);
comment on table public.engine_prisoners is 'Who is locked in which Engine of Chaos: named prisoners from captive cases, anonymous ones from the holder''s exploration. Written by triggers and RPCs only; freed/dispatched are reserved for the rescue and journey writers.';
create unique index engine_prisoners_case_held on public.engine_prisoners (case_id) where state = 'held' and case_id is not null;
create index engine_prisoners_engine_idx on public.engine_prisoners (engine_id, state);
create index engine_prisoners_report_idx on public.engine_prisoners (exploration_report_id) where exploration_report_id is not null;
alter table public.engine_prisoners enable row level security;
create policy engine_prisoners_select on public.engine_prisoners for select to authenticated using (
  public.can_read_warband(holder_warband_id) or (victim_warband_id is not null and public.can_edit_warband(victim_warband_id))
);
grant select on public.engine_prisoners to authenticated;

-- An occupied Engine is locked like a travelling one for the 101 inventory guards (no shrinking,
-- no removal). Further placements into a partly occupied present Engine are still allowed.
create or replace function public.engine_inventory_locked(p_engine_id uuid) returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (select 1 from public.engine_of_chaos_units where id = p_engine_id and state = 'away')
      or exists (select 1 from public.engine_prisoners where engine_id = p_engine_id and state = 'held');
$$;

create function public.engine_places_used(p_engine_id uuid) returns integer language sql stable security definer set search_path = '' as $$
  select coalesce(sum(places), 0)::integer from public.engine_prisoners where engine_id = p_engine_id and state = 'held';
$$;
revoke all on function public.engine_places_used(uuid) from public;

-- ---------------------------------------------------------------------------------------------
-- Placement proposal: the victim's side surrenders exactly the Hero's kit; the holder's stash gains it.
-- ---------------------------------------------------------------------------------------------
create function public.validate_engine_placement_proposal(p_case public.captive_cases, p_choice jsonb, p_owner_changes jsonb, p_captor_changes jsonb, p_advances jsonb)
returns text language plpgsql security definer set search_path = '' as $$
declare
  v public.warbands%rowtype; k public.warbands%rowtype; h public.heroes%rowtype; e public.engine_of_chaos_units%rowtype; item_row public.items%rowtype;
  c jsonb; keys text[]; t text; op text; v_id uuid; d jsonb; key text; qty int; tag text; seen text[] := '{}';
  surrendered jsonb := '{}'::jsonb; gained jsonb := '{}'::jsonb; moved int := 0; hero_items int; places int; used int; kit_text text; msg text;
begin
  if p_case.subject_kind <> 'hero' then raise exception 'Only a captured Hero or hired sword can be locked in an Engine of Chaos for now (henchman placement is a later step).' using errcode = '22023'; end if;
  if jsonb_typeof(coalesce(p_advances, '[]'::jsonb)) <> 'array' or jsonb_array_length(coalesce(p_advances, '[]'::jsonb)) > 0 then raise exception 'Imprisonment awards no experience.' using errcode = '22023'; end if;
  select * into v from public.warbands where id = p_case.victim_warband_id;
  select * into k from public.warbands where id = p_case.captor_warband_id;
  if k.id is null or k.type_rules_id <> 'black_dwarfs' then raise exception 'Only a Chaos Dwarf warband keeps an Engine of Chaos.' using errcode = '22023'; end if;
  if (p_choice->>'engineId') !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' then raise exception 'Choose the Engine that holds the prisoner.' using errcode = '22023'; end if;
  select * into e from public.engine_of_chaos_units where id = (p_choice->>'engineId')::uuid and warband_id = k.id and state <> 'retired';
  if not found then raise exception 'That Engine is not in the captor''s inventory.' using errcode = '22023'; end if;
  if e.state <> 'present' then raise exception '% is away; prisoners can only be locked in an Engine that is with the warband.', e.name using errcode = 'P0001'; end if;
  select * into h from public.heroes where id = p_case.hero_id and warband_id = v.id and status = 'captured';
  if not found then raise exception 'This warrior is no longer recorded as captured.' using errcode = 'P0001'; end if;
  places := case when public.capture_unit_large(public.capture_unit_key(h.unit_type_rules_id, h.is_hired_sword, h.hired_sword_rules_id), h.is_large) then 2 else 1 end;
  used := public.engine_places_used(e.id);
  if used + places > 6 then raise exception '% is full: % of six places are taken and % needs %.', e.name, used, h.name, places using errcode = 'P0001'; end if;
  select count(*) into hero_items from public.items where warband_id = v.id and holder_type = 'hero' and holder_id = h.id;

  for c in select x from jsonb_array_elements(p_owner_changes) x loop
    t := c->>'table'; op := c->>'op'; v_id := (c->>'id')::uuid;
    tag := t || ':' || op || ':' || coalesce(v_id::text, v.id::text);
    if tag = any(seen) then raise exception 'The proposal changes the same row twice (% %).', op, t using errcode = '22023'; end if;
    seen := seen || tag;
    if t = 'items' and op = 'delete' then
      select * into item_row from public.items i where i.id = v_id and i.warband_id = v.id and i.holder_type = 'hero' and i.holder_id = h.id;
      if not found then raise exception 'The proposal changes something imprisonment cannot touch (% % on %).', op, t, coalesce(v_id::text, 'a new row') using errcode = '22023'; end if;
      key := public.captive_item_key(item_row.item_rules_id, item_row.custom_name, item_row.notes);
      surrendered := jsonb_set(surrendered, array[key], to_jsonb(coalesce((surrendered->>key)::int, 0) + item_row.quantity));
      moved := moved + 1;
    else
      raise exception 'Imprisonment only confiscates the prisoner''s equipment; the proposal changes % % on %.', op, t, coalesce(v_id::text, 'a new row') using errcode = '22023';
    end if;
  end loop;
  if moved <> hero_items then raise exception 'All of the prisoner''s equipment is lost to the Chaos Dwarfs: the proposal must hand over every item he carries.' using errcode = '22023'; end if;

  for c in select x from jsonb_array_elements(p_captor_changes) x loop
    t := c->>'table'; op := c->>'op'; v_id := (c->>'id')::uuid; d := coalesce(c->'data', '{}'::jsonb);
    select coalesce(array_agg(x), '{}') into keys from jsonb_object_keys(d) x;
    if t = 'items' and op = 'insert' then
      if coalesce(d->>'holder_type', 'stash') <> 'stash' or nullif(d->>'holder_id', '') is not null then raise exception 'Confiscated equipment goes to the Chaos Dwarf stash.' using errcode = '22023'; end if;
      key := public.captive_item_key(d->>'item_rules_id', d->>'custom_name', d->>'notes'); qty := coalesce((d->>'quantity')::int, 1);
      if qty < 1 or not (surrendered ? key) then raise exception 'The Chaos Dwarfs may only gain what the prisoner carried.' using errcode = '22023'; end if;
      gained := jsonb_set(gained, array[key], to_jsonb(coalesce((gained->>key)::int, 0) + qty));
    elsif t = 'items' and op = 'update' then
      tag := t || ':' || op || ':' || coalesce(v_id::text, '-');
      if tag = any(seen) then raise exception 'The proposal changes the same row twice (% %).', op, t using errcode = '22023'; end if;
      seen := seen || tag;
      select * into item_row from public.items where id = v_id and warband_id = k.id and holder_type = 'stash';
      if not found or not (keys <@ array['quantity']) or coalesce((d->>'quantity')::int, 0) <= item_row.quantity then raise exception 'The proposal changes something imprisonment cannot touch (% % on %).', op, t, coalesce(v_id::text, 'a new row') using errcode = '22023'; end if;
      key := public.captive_item_key(item_row.item_rules_id, item_row.custom_name, item_row.notes);
      if not (surrendered ? key) then raise exception 'The Chaos Dwarfs may only gain what the prisoner carried.' using errcode = '22023'; end if;
      gained := jsonb_set(gained, array[key], to_jsonb(coalesce((gained->>key)::int, 0) + (d->>'quantity')::int - item_row.quantity));
    else
      raise exception 'Imprisonment only confiscates the prisoner''s equipment; the proposal changes % % on %.', op, t, coalesce(v_id::text, 'a new row') using errcode = '22023';
    end if;
  end loop;
  select string_agg(public.captive_kit_label(x.key) || case when (x.value)::int > 1 then ' ×' || x.value else '' end, ', ' order by x.key) into kit_text from jsonb_each_text(surrendered) x;
  if gained <> surrendered then raise exception 'The Chaos Dwarf stash must gain exactly the prisoner''s equipment (%).', coalesce(kit_text, 'nothing') using errcode = '22023'; end if;

  msg := 'Locked in ' || e.name || '. ' || h.name || ' (' || v.name || ') stays captured and is imprisoned in the Engine of Chaos of ' || k.name
    || ', taking ' || case when places = 1 then 'one place' else 'two places (Large)' end || ' (' || used + places || ' of 6 used). '
    || case when hero_items > 0 then 'His equipment is lost to ' || k.name || ': ' || kit_text || '.' else 'He carried no equipment.' end
    || ' Ransom, exchange or sale need the placement reversed first.';
  if length(msg) > 30000 then raise exception 'The consent text is too long to record; shorten the equipment annotations and try again.' using errcode = '22023'; end if;
  return msg;
end $$;
revoke all on function public.validate_engine_placement_proposal(public.captive_cases, jsonb, jsonb, jsonb, jsonb) from public;

create or replace function public.validate_captive_proposal(p_case public.captive_cases, p_choice jsonb, p_owner_changes jsonb, p_captor_changes jsonb, p_advances jsonb default '[]'::jsonb)
returns text language plpgsql security definer set search_path = '' as $$
begin
  if jsonb_typeof(p_choice) <> 'object' then raise exception 'Choose an outcome.' using errcode = '22023'; end if;
  if p_choice->>'kind' = 'kidnapped' then
    return public.validate_kidnapped_proposal(p_case, p_choice, p_owner_changes, p_captor_changes, coalesce(p_advances, '[]'::jsonb));
  end if;
  if p_choice->>'kind' = 'engine_placement' then
    return public.validate_engine_placement_proposal(p_case, p_choice, p_owner_changes, p_captor_changes, coalesce(p_advances, '[]'::jsonb));
  end if;
  if p_choice->>'kind' = 'exchange' and p_choice ? 'otherCaseId' then
    return public.validate_exchange_proposal(p_case, p_choice, p_owner_changes, p_captor_changes, coalesce(p_advances, '[]'::jsonb));
  end if;
  if p_case.subject_kind = 'companion' then
    return public.validate_companion_proposal(p_case, p_choice, p_owner_changes, p_captor_changes, coalesce(p_advances, '[]'::jsonb));
  end if;
  if p_case.subject_kind = 'henchman' and p_case.source = 'forced_capture' then
    return public.validate_forced_henchman_proposal(p_case, p_choice, p_owner_changes, p_captor_changes, coalesce(p_advances, '[]'::jsonb));
  end if;
  if p_case.subject_kind <> 'hero' then raise exception 'A lost henchman can only be resolved through Kidnapped!.' using errcode = '22023'; end if;
  return public.validate_core_captive_proposal(p_case, p_choice, p_owner_changes, p_captor_changes, coalesce(p_advances, '[]'::jsonb));
end $$;
revoke all on function public.validate_captive_proposal(public.captive_cases, jsonb, jsonb, jsonb, jsonb) from public;

-- ---------------------------------------------------------------------------------------------
-- Acceptance: the prisoner takes his places under the inventory locks. apply_captive_proposal has
-- already moved the kit and stored before_snapshot when the proposal's state becomes 'accepted',
-- so the custody snapshot carries the Hero and his original item rows exactly as they stood.
-- ---------------------------------------------------------------------------------------------
create function public.engine_prisoner_on_proposal() returns trigger language plpgsql security definer set search_path = '' as $$
declare c public.captive_cases%rowtype; e public.engine_of_chaos_units%rowtype; h public.heroes%rowtype; places int; used int; kit jsonb; original jsonb; hero_before jsonb;
begin
  if new.choice->>'kind' <> 'engine_placement' or old.state = new.state then return new; end if;
  if new.state = 'accepted' then
    select * into c from public.captive_cases where id = new.case_id;
    select * into e from public.engine_of_chaos_units where id = (new.choice->>'engineId')::uuid;
    if e.id is null then raise exception 'That Engine is not in the captor''s inventory.' using errcode = 'P0001'; end if;
    if new.before_snapshot is null then raise exception 'The placement was accepted without its roster snapshot.' using errcode = 'P0001'; end if;
    -- Lock order from 101: the stock item row, then this stock's Engine rows by id.
    perform id from public.items where id = e.inventory_item_id for update;
    perform id from public.engine_of_chaos_units where inventory_item_id = e.inventory_item_id order by id for update;
    select * into e from public.engine_of_chaos_units where id = e.id;
    if e.state <> 'present' then raise exception '% is away; prisoners can only be locked in an Engine that is with the warband.', e.name using errcode = 'P0001'; end if;
    select * into h from public.heroes where id = c.hero_id;
    places := case when public.capture_unit_large(public.capture_unit_key(h.unit_type_rules_id, h.is_hired_sword, h.hired_sword_rules_id), h.is_large) then 2 else 1 end;
    used := public.engine_places_used(e.id);
    if used + places > 6 then raise exception '% is full: % of six places are taken and % needs %.', e.name, used, c.hero_name, places using errcode = 'P0001'; end if;
    select x into hero_before from jsonb_array_elements(new.before_snapshot->'heroes') x where (x->>'id')::uuid = c.hero_id;
    select coalesce(jsonb_agg(x order by x->>'id'), '[]'::jsonb) into original from jsonb_array_elements(new.before_snapshot->'items') x
      where (x->>'warband_id')::uuid = c.victim_warband_id and x->>'holder_type' = 'hero' and (x->>'holder_id')::uuid = c.hero_id;
    select coalesce(jsonb_agg(x), '[]'::jsonb) into kit from jsonb_array_elements(new.captor_changes) x where x->>'table' = 'items';
    insert into public.engine_prisoners (engine_id, holder_warband_id, case_id, victim_warband_id, name, large, places, snapshot, confiscated, proposal_id, placed_by, history)
      values (e.id, c.captor_warband_id, c.id, c.victim_warband_id, c.hero_name, places = 2, places,
              jsonb_build_object('hero', coalesce(hero_before, to_jsonb(h) - 'updated_at'), 'items', original, 'report_id', c.report_id, 'report_revision', c.report_revision, 'source', c.source),
              kit, new.id, auth.uid(),
              jsonb_build_array(jsonb_build_object('event', 'placed', 'at', now(), 'by', auth.uid(), 'proposal_id', new.id)));
    update public.engine_of_chaos_units set history = history || jsonb_build_object('event', 'prisoner_placed', 'at', now(), 'by', auth.uid(), 'name', c.hero_name, 'places', places) where id = e.id;
  elsif new.state = 'reversed' then
    -- reverse_captive_resolution has normally done this already; a GM release-only path lands here.
    with done as (
      update public.engine_prisoners set state = 'reversed', released_at = now(), release_reason = new.reason,
             history = history || jsonb_build_object('event', 'placement_reversed', 'at', now(), 'by', auth.uid(), 'reason', new.reason)
        where proposal_id = new.id and state = 'held' returning engine_id, name)
    update public.engine_of_chaos_units u set history = u.history || jsonb_build_object('event', 'prisoner_released', 'at', now(), 'by', auth.uid(), 'name', done.name, 'reason', new.reason)
      from done where u.id = done.engine_id;
  end if;
  return new;
end $$;
revoke all on function public.engine_prisoner_on_proposal() from public;
create trigger engine_prisoner_on_proposal after update of state on public.captive_proposals for each row execute function public.engine_prisoner_on_proposal();

-- A placement is custody, not an outcome: the case reads 'held', never 'resolved'.
create function public.hold_case_for_engine() returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if new.state = 'resolved' and new.resolution_kind = 'engine_placement' then new.state := 'held'; end if;
  return new;
end $$;
revoke all on function public.hold_case_for_engine() from public;
create trigger hold_case_for_engine before update of state on public.captive_cases for each row execute function public.hold_case_for_engine();

-- A held Hero never reappears through the legacy form: his status cannot leave 'captured' while
-- the placement stands (the 090 reversal runs under stirheim.captive_apply and is exempt).
create function public.guard_held_hero() returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if current_setting('stirheim.captive_apply', true) = '1' then return new; end if;
  if old.status = 'captured' and new.status <> 'captured'
     and exists (select 1 from public.captive_cases c where c.hero_id = new.id and c.subject_kind = 'hero' and c.state = 'held') then
    raise exception '% is locked in an Engine of Chaos. Reverse the imprisonment from the warband page before changing his status.', old.name using errcode = 'P0001';
  end if;
  return new;
end $$;
revoke all on function public.guard_held_hero() from public;
create trigger guard_held_hero before update of status on public.heroes for each row execute function public.guard_held_hero();

-- ---------------------------------------------------------------------------------------------
-- Report guard and reversal learn the 'held' state; the reversal restores items in place.
-- ---------------------------------------------------------------------------------------------
create or replace function public.guard_captive_report() returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if tg_op = 'DELETE' or (old.undo is not null and new.undo is null) then
    if exists (select 1 from public.captive_cases where report_id = old.id and state in ('resolved', 'held') and resolution_kind is distinct from 'external')
       or exists (select 1 from public.captive_proposals where state = 'accepted' and old.id = any(linked_report_ids)) then
      raise exception 'A captive outcome recorded between two warbands depends on this report (it was filed before the ransom, exchange, sale, sacrifice or imprisonment was agreed). Reverse that outcome from the warband page first (or ask the campaign GM to release it), then withdraw or correct the report.';
    end if;
    if exists (select 1 from public.engine_prisoners where exploration_report_id = old.id and state = 'held') then
      raise exception 'Prisoners found in this exploration are still locked in an Engine of Chaos. Reverse their placement from the warband page before withdrawing or correcting the report.';
    end if;
    update public.captive_proposals set state = 'stale', resolved_at = now(), reason = 'The source report was withdrawn or corrected.'
      where state = 'proposed' and case_id in (select id from public.captive_cases where report_id = old.id);
    update public.captive_cases set state = 'withdrawn', resolved_at = now(), resolution_message = 'The source report was withdrawn or corrected.'
      where report_id = old.id and (state in ('unassigned', 'open') or (state = 'resolved' and resolution_kind = 'external'));
  end if;
  if tg_op = 'DELETE' then return old; end if;
  return new;
end $$;

create or replace function public.reverse_captive_resolution(p_case_id uuid, p_reason text, p_release_only boolean default false)
returns void language plpgsql security definer set search_path = '' as $$
declare c public.captive_cases%rowtype; pr public.captive_proposals%rowtype; v_gm boolean; v_current jsonb; v_msg text; v_found boolean;
begin
  if auth.uid() is null then raise exception 'Sign in first.' using errcode = '42501'; end if;
  if char_length(btrim(coalesce(p_reason, ''))) < 5 then raise exception 'Explain why the outcome is being reversed.' using errcode = 'P0001'; end if;
  select * into c from public.captive_cases where id = p_case_id;
  if not found then raise exception 'Captive case not found.' using errcode = 'P0002'; end if;
  perform public.lock_captive_context(c.match_id, c.victim_warband_id, c.captor_warband_id);
  select * into c from public.captive_cases where id = p_case_id for update;
  if c.state not in ('resolved', 'held') then raise exception 'This captive case has no recorded outcome to reverse.' using errcode = 'P0001'; end if;
  v_gm := public.is_campaign_gm(public.match_campaign(c.match_id));
  if p_release_only and not v_gm then raise exception 'Only the campaign GM can release a captive outcome without restoring the rosters.' using errcode = '42501'; end if;
  if not (v_gm or (public.can_edit_warband(c.victim_warband_id) and public.can_edit_warband(c.captor_warband_id))) then
    raise exception 'Only the campaign GM, or a player of both warbands, can reverse a recorded captive outcome.' using errcode = '42501';
  end if;
  select * into pr from public.captive_proposals where case_id = c.id and state = 'accepted' order by resolved_at desc limit 1 for update;
  v_found := found;
  if p_release_only or not v_found or pr.before_snapshot is null then
    if not p_release_only then
      raise exception 'This outcome was recorded outside the proposal flow, so it cannot be restored automatically. The campaign GM can release it and correct both rosters by hand.' using errcode = 'P0001';
    end if;
    v_msg := 'Released by the GM without restoring rosters: ' || btrim(p_reason);
    if v_found then update public.captive_proposals set state = 'reversed', responded_by = auth.uid(), resolved_at = now(), reason = v_msg where id = pr.id; end if;
    update public.captive_cases set state = 'withdrawn', resolved_at = now(), resolution_message = v_msg,
           history = history || jsonb_build_object('at', now(), 'by', auth.uid(), 'event', 'released', 'reason', btrim(p_reason)) where id = c.id;
  else
    perform id from public.heroes where warband_id in (c.victim_warband_id, c.captor_warband_id) order by id for update;
    perform id from public.henchman_groups where warband_id in (c.victim_warband_id, c.captor_warband_id) order by id for update;
    perform id from public.items where warband_id in (c.victim_warband_id, c.captor_warband_id) order by id for update;
    v_current := public.captive_roster_snapshot(c.victim_warband_id, c.captor_warband_id);
    if v_current is distinct from pr.after_snapshot then
      raise exception 'One of the warbands has changed since this outcome was recorded, so it cannot be restored automatically. The campaign GM can release the report dependency and correct both rosters by hand.' using errcode = 'P0001';
    end if;
    if exists (select 1 from public.pending_advances where id = any(pr.advance_ids) and resolved_at is not null) then
      raise exception 'An advance rolled from this outcome has already been resolved. The campaign GM must release and reconcile by hand.' using errcode = 'P0001';
    end if;
    v_msg := 'Captive outcome reversed: ' || btrim(p_reason);
    perform set_config('stirheim.audit_reason', v_msg, true);
    perform set_config('stirheim.captive_apply', '1', true);
    -- Custody ends before the rosters move, so the Engine's stock row is not locked by its prisoner.
    with done as (
      update public.engine_prisoners set state = 'reversed', released_at = now(), release_reason = btrim(p_reason),
             history = history || jsonb_build_object('event', 'placement_reversed', 'at', now(), 'by', auth.uid(), 'reason', btrim(p_reason))
        where proposal_id = pr.id and state = 'held' returning engine_id, name)
    update public.engine_of_chaos_units u set history = u.history || jsonb_build_object('event', 'prisoner_released', 'at', now(), 'by', auth.uid(), 'name', done.name, 'reason', btrim(p_reason))
      from done where u.id = done.engine_id;
    delete from public.pending_advances where id = any(pr.advance_ids);
    delete from public.items where warband_id in (c.victim_warband_id, c.captor_warband_id)
      and id not in (select (x->>'id')::uuid from jsonb_array_elements(pr.before_snapshot->'items') x);
    delete from public.heroes where warband_id in (c.victim_warband_id, c.captor_warband_id)
      and id not in (select (x->>'id')::uuid from jsonb_array_elements(pr.before_snapshot->'heroes') x);
    delete from public.henchman_groups where warband_id in (c.victim_warband_id, c.captor_warband_id)
      and id not in (select (x->>'id')::uuid from jsonb_array_elements(pr.before_snapshot->'henchman_groups') x);
    update public.warbands w set gold = r.gold, wyrdstone = r.wyrdstone, veteran_pool = r.veteran_pool, notes = r.notes
      from (select (jsonb_populate_record(null::public.warbands, x)).* from jsonb_array_elements(pr.before_snapshot->'warbands') x) r where r.id = w.id;
    update public.heroes h set warband_id = r.warband_id, name = r.name, is_hired_sword = r.is_hired_sword, unit_type_rules_id = r.unit_type_rules_id, hired_sword_rules_id = r.hired_sword_rules_id,
           stats = r.stats, xp = r.xp, level_ups = r.level_ups, skill_tables = r.skill_tables, skills = r.skills, spells = r.spells, injuries = r.injuries, flags = r.flags,
           equipment_locked = r.equipment_locked, is_large = r.is_large, status = r.status, notes = r.notes, sort_order = r.sort_order
      from (select (jsonb_populate_record(null::public.heroes, x)).* from jsonb_array_elements(pr.before_snapshot->'heroes') x) r where r.id = h.id;
    insert into public.heroes select (jsonb_populate_record(null::public.heroes, x || jsonb_build_object('updated_at', now()))).* from jsonb_array_elements(pr.before_snapshot->'heroes') x
      where not exists (select 1 from public.heroes h where h.id = (x->>'id')::uuid);
    update public.henchman_groups g set warband_id = r.warband_id, name = r.name, unit_type_rules_id = r.unit_type_rules_id, size = r.size, stats = r.stats, xp = r.xp, level_ups = r.level_ups,
           stat_increases = r.stat_increases, is_large = r.is_large, notes = r.notes, sort_order = r.sort_order, model_names = r.model_names, campaign_state = r.campaign_state
      from (select (jsonb_populate_record(null::public.henchman_groups, x)).* from jsonb_array_elements(pr.before_snapshot->'henchman_groups') x) r where r.id = g.id;
    insert into public.henchman_groups select (jsonb_populate_record(null::public.henchman_groups, x || jsonb_build_object('updated_at', now()))).* from jsonb_array_elements(pr.before_snapshot->'henchman_groups') x
      where not exists (select 1 from public.henchman_groups g where g.id = (x->>'id')::uuid);
    -- Items in place: surviving rows keep their ids (101 keys Engine identities to the stock row).
    update public.items i set warband_id = r.warband_id, holder_type = r.holder_type, holder_id = r.holder_id, item_rules_id = r.item_rules_id, custom_name = r.custom_name, quantity = r.quantity, notes = r.notes
      from (select (jsonb_populate_record(null::public.items, x)).* from jsonb_array_elements(pr.before_snapshot->'items') x) r
      where r.id = i.id and (i.warband_id, i.holder_type, i.holder_id, i.item_rules_id, i.custom_name, i.quantity, i.notes) is distinct from (r.warband_id, r.holder_type, r.holder_id, r.item_rules_id, r.custom_name, r.quantity, r.notes);
    insert into public.items select (jsonb_populate_record(null::public.items, x || jsonb_build_object('updated_at', now()))).* from jsonb_array_elements(pr.before_snapshot->'items') x
      where not exists (select 1 from public.items i where i.id = (x->>'id')::uuid);
    update public.captive_proposals set state = 'reversed', responded_by = auth.uid(), resolved_at = now(), reason = btrim(p_reason) where id = pr.id;
    update public.captive_cases set state = 'open', resolved_at = null, resolution_kind = null, resolution_message = '',
           history = history || jsonb_build_object('at', now(), 'by', auth.uid(), 'event', 'reversed', 'proposal_id', pr.id, 'reason', btrim(p_reason)) where id = c.id;
    update public.captive_cases set state = 'open', resolved_at = null, resolution_kind = null, resolution_message = '', resolved_by_proposal = null,
           history = history || jsonb_build_object('at', now(), 'by', auth.uid(), 'event', 'reversed_by_exchange', 'proposal_id', pr.id) where resolved_by_proposal = pr.id;
  end if;
  update public.match_reports set notes = concat_ws(E'\n', nullif(notes, ''), c.hero_name || ': ' || v_msg) where id = c.report_id;
  insert into public.app_notifications (user_id, kind, title, body, href, dedupe_key)
    select w.owner_id, 'captive', left(c.hero_name || ': captive outcome reversed', 140), left(v_msg, 2000), '/warbands/' || w.id, 'captive:' || c.id || ':reversed:' || w.id || ':' || extract(epoch from now())::bigint
      from public.warbands w where w.id in (c.victim_warband_id, c.captor_warband_id) on conflict do nothing;
end $$;

-- ---------------------------------------------------------------------------------------------
-- Anonymous prisoners from the holder's own exploration (core chart: Straggler = one, Prisoners =
-- D3). No other roster is touched, so the holder's player or the GM records them; the count is
-- bounded by the report's location and its D3 across every Engine, and the D3 is fixed by the first
-- placement for that report. Empire in Flames locations are a follow-on, not free text.
-- ---------------------------------------------------------------------------------------------
create function public.place_anonymous_prisoners(p_engine_id uuid, p_report_id uuid, p_prisoners jsonb, p_count_roll integer default null)
returns setof uuid language plpgsql security definer set search_path = '' as $$
declare e public.engine_of_chaos_units%rowtype; r public.match_reports%rowtype; p jsonb; used int; v_id uuid; v_location text; v_allowed int; v_taken int; v_roll int; v_existing_roll int;
begin
  if auth.uid() is null then raise exception 'Sign in first.' using errcode = '42501'; end if;
  if jsonb_typeof(p_prisoners) <> 'array' or jsonb_array_length(p_prisoners) = 0 then raise exception 'List the prisoners to lock up, each with a name.' using errcode = '22023'; end if;
  select * into e from public.engine_of_chaos_units where id = p_engine_id and state <> 'retired';
  if not found then raise exception 'That Engine is not in the inventory.' using errcode = 'P0002'; end if;
  if not public.can_edit_warband(e.warband_id) then raise exception 'Only this warband''s player or the campaign GM locks prisoners in its Engine.' using errcode = '42501'; end if;
  if not exists (select 1 from public.warbands where id = e.warband_id and type_rules_id = 'black_dwarfs') then raise exception 'Only a Chaos Dwarf warband keeps an Engine of Chaos.' using errcode = '22023'; end if;
  select * into r from public.match_reports where id = p_report_id and warband_id = e.warband_id and undo is not null;
  if not found then raise exception 'Prisoners come from this warband''s own applied report of the battle.' using errcode = '22023'; end if;
  -- Report rows first (as 089/090), then the stock row, then the Engine rows by id.
  perform id from public.match_reports where match_id = r.match_id order by id for update;
  perform id from public.items where id = e.inventory_item_id for update;
  perform id from public.engine_of_chaos_units where inventory_item_id = e.inventory_item_id order by id for update;
  select * into r from public.match_reports where id = p_report_id;
  select * into e from public.engine_of_chaos_units where id = p_engine_id;
  if e.state <> 'present' then raise exception '% is away; prisoners can only be locked in an Engine that is with the warband.', e.name using errcode = 'P0001'; end if;
  v_location := r.exploration->>'locationId';
  if v_location = 'straggler' then
    v_allowed := 1; v_roll := null;
    if p_count_roll is not null then raise exception 'A Straggler is one prisoner; no D3 applies.' using errcode = '22023'; end if;
    if exists (select 1 from jsonb_array_elements_text(coalesce(r.exploration->'benefits', '[]'::jsonb)) b where b = 'straggler') then
      raise exception 'This report already used the Straggler for insight into the city (an extra exploration die). Correct the report before locking him up.' using errcode = 'P0001';
    end if;
  elsif v_location = 'prisoners' then
    select (snapshot->>'count_roll')::int into v_existing_roll from public.engine_prisoners where exploration_report_id = r.id and state <> 'reversed' order by placed_at limit 1;
    if v_existing_roll is not null then
      if p_count_roll is not null and p_count_roll <> v_existing_roll then raise exception 'The Prisoners D3 for this report was already recorded as %; the count cannot be re-rolled.', v_existing_roll using errcode = 'P0001'; end if;
      v_roll := v_existing_roll;
    else
      if p_count_roll is null or p_count_roll not between 1 and 3 then raise exception 'Roll a D3 for how many prisoners were found (1 to 3).' using errcode = '22023'; end if;
      v_roll := p_count_roll;
    end if;
    v_allowed := v_roll;
  elsif v_location is null then
    raise exception 'This report found no prisoners in its exploration.' using errcode = 'P0001';
  else
    raise exception 'Only the core chart''s Straggler and Prisoners results place anonymous prisoners for now (Empire in Flames locations are a later step).' using errcode = 'P0001';
  end if;
  select coalesce(sum(1), 0) into v_taken from public.engine_prisoners where exploration_report_id = r.id and state <> 'reversed';
  if v_taken + jsonb_array_length(p_prisoners) > v_allowed then
    raise exception 'This exploration yields % prisoner%; % already locked up, so % more cannot be added.', v_allowed, case when v_allowed = 1 then '' else 's' end, v_taken, jsonb_array_length(p_prisoners) using errcode = 'P0001';
  end if;
  used := public.engine_places_used(e.id);
  for p in select x from jsonb_array_elements(p_prisoners) x loop
    if jsonb_typeof(p) <> 'object' or char_length(btrim(coalesce(p->>'name', ''))) not between 1 and 80 then raise exception 'Each prisoner needs a name of 1 to 80 characters.' using errcode = '22023'; end if;
    if coalesce((p->>'large')::boolean, false) then raise exception 'Prisoners found exploring are ordinary humans and take one place each.' using errcode = '22023'; end if;
    if used + 1 > 6 then raise exception '% is full: % of six places are taken and % needs 1.', e.name, used, btrim(p->>'name') using errcode = 'P0001'; end if;
    used := used + 1;
    insert into public.engine_prisoners (engine_id, holder_warband_id, exploration_report_id, name, large, places, snapshot, placed_by, history)
      values (e.id, e.warband_id, r.id, btrim(p->>'name'), false, 1,
              jsonb_build_object('anonymous', true, 'report_id', r.id, 'report_revision', r.revision, 'location', v_location, 'count_roll', v_roll, 'allowed', v_allowed),
              auth.uid(), jsonb_build_array(jsonb_build_object('event', 'placed_from_exploration', 'at', now(), 'by', auth.uid(), 'report_id', r.id, 'location', v_location)))
      returning id into v_id;
    return next v_id;
  end loop;
  update public.engine_of_chaos_units set history = history || jsonb_build_object('event', 'prisoners_placed_from_exploration', 'at', now(), 'by', auth.uid(), 'count', jsonb_array_length(p_prisoners), 'report_id', r.id, 'location', v_location) where id = e.id;
  return;
end $$;
revoke all on function public.place_anonymous_prisoners(uuid, uuid, jsonb, integer) from public;
grant execute on function public.place_anonymous_prisoners(uuid, uuid, jsonb, integer) to authenticated;

-- Undo an anonymous placement (mistaken entry, or to withdraw the report). Named prisoners are
-- reversed through reverse_captive_resolution, which restores the kit.
create function public.reverse_anonymous_placement(p_prisoner_id uuid, p_reason text)
returns void language plpgsql security definer set search_path = '' as $$
declare pz public.engine_prisoners%rowtype;
begin
  if auth.uid() is null then raise exception 'Sign in first.' using errcode = '42501'; end if;
  if char_length(btrim(coalesce(p_reason, ''))) < 5 then raise exception 'Explain why the placement is being reversed.' using errcode = 'P0001'; end if;
  select * into pz from public.engine_prisoners where id = p_prisoner_id;
  if not found then raise exception 'Prisoner not found.' using errcode = 'P0002'; end if;
  if pz.exploration_report_id is null then raise exception 'This prisoner came from a captive case: reverse the imprisonment from that case so his equipment returns.' using errcode = 'P0001'; end if;
  if not public.can_edit_warband(pz.holder_warband_id) then raise exception 'Only this warband''s player or the campaign GM changes its Engine''s prisoners.' using errcode = '42501'; end if;
  perform id from public.match_reports where id = pz.exploration_report_id for update;
  perform id from public.items where id = (select inventory_item_id from public.engine_of_chaos_units where id = pz.engine_id) for update;
  select * into pz from public.engine_prisoners where id = p_prisoner_id for update;
  if pz.state <> 'held' then raise exception 'This prisoner is no longer held (%).', pz.state using errcode = 'P0001'; end if;
  update public.engine_prisoners set state = 'reversed', released_at = now(), release_reason = btrim(p_reason),
         history = history || jsonb_build_object('event', 'placement_reversed', 'at', now(), 'by', auth.uid(), 'reason', btrim(p_reason)) where id = pz.id;
  update public.engine_of_chaos_units set history = history || jsonb_build_object('event', 'prisoner_released', 'at', now(), 'by', auth.uid(), 'name', pz.name, 'reason', btrim(p_reason)) where id = pz.engine_id;
end $$;
revoke all on function public.reverse_anonymous_placement(uuid, text) from public;
grant execute on function public.reverse_anonymous_placement(uuid, text) to authenticated;
