-- Generated by scripts/generate-warband-leaders.mjs; do not edit historical migrations.
create or replace function public.warband_leader_unit(p_type_rules_id text) returns text language sql immutable as $$
  select case p_type_rules_id
    when 'amazons_lustria' then 'amazons_lustria_serpent_priestess'
    when 'amazons_mordheim' then 'amazons_mordheim_priestess'
    when 'arabian_tomb_raiders' then 'arabian_tomb_raiders_sheikh'
    when 'averlander_mercenaries' then 'averlander_captain'
    when 'battle_monks_of_cathay' then 'battle_monks_emissary'
    when 'beastmen_raiders' then 'beastmen_chieftain'
    when 'black_dwarfs' then 'black_dwarfs_sorcerer'
    when 'black_orcs' then 'black_orcs_black_orc_boss'
    when 'bretonnian_chapel_guard' then 'bretonnian_questing_knight'
    when 'bretonnian_knights' then 'bretonnian_knights_questing_knight'
    when 'carnival_of_chaos' then 'carnival_of_chaos_master'
    when 'court_of_the_profane_pleasures' then null
    when 'cult_of_the_possessed' then 'cult_of_the_possessed_magister'
    when 'dark_elves' then 'dark_elves_high_born'
    when 'dreamwalkers_cult_of_morr' then 'dreamwalkers_priest_of_morr'
    when 'druchii' then 'druchii_noble'
    when 'dwarf_rangers' then 'dwarf_rangers_runesmith'
    when 'dwarf_slayer_cult' then 'dwarf_slayer_cult_giant_slayer'
    when 'dwarf_treasure_hunters' then 'dwarf_treasure_hunters_noble'
    when 'forest_goblins' then 'forest_goblins_chieftain'
    when 'grave_robbers' then 'grave_robbers_graver'
    when 'gunnery_school_of_nuln' then 'gunnery_school_of_nuln_senior_gunnery_officer'
    when 'halflings' then 'halflings_elder'
    when 'hochland_bandits' then 'hochland_bandits_bandit_prince'
    when 'horned_hunters' then 'horned_hunters_horned_hunter'
    when 'imperial_outriders' then 'imperial_outriders_knight'
    when 'kislevites' then 'kislevites_druzhina_captain'
    when 'lizardmen' then 'lizardmen_skink_priest'
    when 'lustrian_reavers' then null
    when 'maneaters' then 'maneaters_captain'
    when 'marauders_of_chaos' then 'marauders_chieftain'
    when 'masters_of_horror' then 'masters_of_horror_mad_scientist'
    when 'mazzalupo' then 'mazzalupo_wandering_knight'
    when 'mercenaries_marienburg' then 'mercenaries_marienburg_captain'
    when 'mercenaries_middenheim' then 'mercenaries_middenheim_captain'
    when 'mercenaries_ostermark' then 'mercenaries_ostermark_captain'
    when 'mercenaries_reikland' then 'mercenaries_reikland_captain'
    when 'merchant_caravans' then 'merchant_merchant'
    when 'mootlanders' then 'mootlanders_moot_elder'
    when 'necrarchs_the_soul_stealers' then 'necrarchs_necrarch_vampire'
    when 'night_goblins' then 'night_goblins_big_boss'
    when 'night_goblins_web' then 'night_goblins_web_boss'
    when 'nipponese_expedition' then 'nipponese_hatamoto'
    when 'norse_explorers' then 'norse_jarl'
    when 'ogre_hunting_party' then 'ogre_hunting_party_ogre_hunter'
    when 'orc_mob' then 'orc_mob_boss'
    when 'order_of_the_mare' then 'paragon'
    when 'ostlander_mercenaries' then 'ostlander_elder'
    when 'outlaws_of_stirwood_forest' then 'outlaws_bandit_leader'
    when 'outlaws_of_stirwood_forest_redux' then 'bandit_leader'
    when 'pirates' then 'pirates_captain'
    when 'pit_fighters' then 'pit_fighters_pit_king'
    when 'protectorate_of_sigmar' then 'warrior_priest'
    when 'shadow_warriors' then 'shadow_warriors_shadow_master'
    when 'sisters_of_sigmar' then 'sisters_of_sigmar_matriarch'
    when 'skaven_of_clan_eshin' then 'skaven_assassin_adept'
    when 'skaven_of_clan_moulder' then 'packmaster'
    when 'skaven_of_clan_pestilens' then 'skaven_pestilens_plague_priest'
    when 'snotlings' then 'bullied_goblin'
    when 'sorcerous_society' then 'magus'
    when 'survivors_of_strigos' then 'strigoi_vampire'
    when 'the_cursed_cavalcade' then 'cursed_cavalcade_aristocrat'
    when 'the_restless_dead' then 'restless_dead_liche'
    when 'the_restless_dead_variant' then 'restless_dead_variant_liche'
    when 'the_sons_of_hashut' then 'sons_of_hashut_apprentice_sorcerer'
    when 'the_undead' then 'undead_vampire'
    when 'tileans_miragleans' then 'tileans_miragleans_captain'
    when 'tileans_remasens' then 'tileans_remasens_captain'
    when 'tileans_trantios' then 'tileans_trantios_captain'
    when 'tomb_guardians' then 'tomb_guardians_tomb_lord'
    when 'vampire_hunters_of_sylvania' then 'vampire_hunter'
    when 'witch_hunters' then 'witch_hunters_captain'
    when 'wood_elves_of_athel_loren' then 'hunt_master'
    else null end;
$$;

-- Mirror currentLeader(), including the Dreamer taking precedence over the Priest.
-- Preserve the existing private helper's execution privileges.
create or replace function public.warband_leader(p_warband_id uuid) returns uuid language plpgsql stable security definer set search_path = '' as $$
declare unit text; band_type text; v_id uuid;
begin
  select type_rules_id into band_type from public.warbands where id = p_warband_id;
  if band_type = 'dreamwalkers_cult_of_morr' then
    select id into v_id from public.heroes where warband_id = p_warband_id and status = 'active' and not is_hired_sword
      and unit_type_rules_id in ('dreamwalkers_dreamer', 'dreamwalkers_priest_of_morr')
      order by (unit_type_rules_id = 'dreamwalkers_dreamer') desc, created_at, id limit 1;
    return v_id;
  end if;
  unit := public.warband_leader_unit(band_type);
  if unit is null then raise exception 'The leader of this warband type is not catalogued yet.' using errcode = 'P0001'; end if;
  select id into v_id from public.heroes where warband_id = p_warband_id and status = 'active' and not is_hired_sword and unit_type_rules_id = unit order by created_at, id limit 1;
  if v_id is null then select id into v_id from public.heroes where warband_id = p_warband_id and status = 'active' and not is_hired_sword and flags->>'leaderRoleId' = unit order by created_at, id limit 1; end if;
  if v_id is null then select id into v_id from public.heroes where warband_id = p_warband_id and status = 'active' and not is_hired_sword and coalesce((flags->>'temporaryLeader')::boolean, false) order by created_at, id limit 1; end if;
  return v_id;
end $$;
-- Supabase can grant API roles directly through default privileges. Revoking
-- PUBLIC alone does not remove those grants from this private roster helper.
revoke all on function public.warband_leader(uuid) from public, anon, authenticated;
