// Convert downloaded mordheimer.net Docusaurus pages to Markdown, grouped into reference files.
import fs from "node:fs";
import path from "node:path";
import * as cheerio from "cheerio";
import TurndownService from "turndown";
import { gfm } from "turndown-plugin-gfm";

const here = path.dirname(new URL(import.meta.url).pathname);
const scrapeDir = path.join(here, "scrape");
const outDir = process.argv[2];
if (!outDir) throw new Error("usage: node convert.mjs <outDir>");

const td = new TurndownService({ headingStyle: "atx", codeBlockStyle: "fenced", bulletListMarker: "-" });
td.use(gfm);
// Drop Docusaurus chrome that can sit inside <article>.
td.remove(["script", "style", "nav", "button"]);
// Heading anchor hash links render as "#" text otherwise.
td.addRule("anchorHash", {
  filter: (node) => node.nodeName === "A" && /hash-link|anchor/.test(node.getAttribute("class") || ""),
  replacement: () => "",
});
// Tooltip spans are just the item name.
td.addRule("tooltip", {
  filter: (node) => node.nodeName === "SPAN" && /tooltip/.test(node.getAttribute("class") || ""),
  replacement: (content) => content,
});

function urlFromFile(f) {
  return "https://mordheimer.net/docs/" + f.replace(/\.html$/, "").replace(/__/g, "/");
}

function pageToMarkdown(file) {
  const html = fs.readFileSync(path.join(scrapeDir, file), "utf8");
  const $ = cheerio.load(html);
  const article = $("article");
  if (!article.length) return null;
  // Remove pagination, breadcrumbs, edit links, TOC.
  article.find(".pagination-nav, .theme-doc-breadcrumbs, .theme-doc-footer, .theme-doc-toc-mobile, .tableOfContents_bqdL, .theme-edit-this-page").remove();
  const title = article.find("h1").first().text().trim();
  let md = td.turndown(article.html());
  // Demote every heading one level so the page title becomes ## and its sections ###/####.
  md = md.replace(/^(#{1,5}) /gm, "#$1 ");
  md = md.replace(/\n{3,}/g, "\n\n").trim();
  return { title, url: urlFromFile(file), md };
}

const files = fs.readdirSync(scrapeDir).filter((f) => f.endsWith(".html")).sort();
const groups = {
  "04-hired-swords.md": (f) => f.startsWith("campaigns__hired-swords"),
  "05-dramatis-personae.md": (f) => f.startsWith("campaigns__dramatis-personae"),
  "06-scenarios.md": (f) => f.startsWith("campaigns__scenarios__"),
  "03a-income-page-rescrape.md": (f) => f === "campaigns__income.html",
};

const stamp = new Date().toISOString().slice(0, 10);
const summary = {};
for (const [outName, match] of Object.entries(groups)) {
  const pages = files.filter(match).map(pageToMarkdown).filter(Boolean);
  // Order: index page first, then grades / sources alphabetically (already sorted by filename).
  const parts = [
    `# ${outName.replace(/^\d+a?-/, "").replace(/\.md$/, "").replace(/-/g, " ")} — mordheimer.net rescrape (${stamp})`,
    "",
    `Verbatim conversion of ${pages.length} page(s) from mordheimer.net (fan-compiled community Mordheim rules, not official Games Workshop material). Each section starts with a **Source:** link to the live page. Generated by scratchpad/convert.mjs; do not hand-edit — re-run the scrape instead.`,
    "",
  ];
  for (const p of pages) {
    parts.push(`\n---\n\n**Source:** ${p.url}\n\n${p.md}\n`);
  }
  fs.writeFileSync(path.join(outDir, outName), parts.join("\n"));
  summary[outName] = { pages: pages.length, bytes: fs.statSync(path.join(outDir, outName)).size, titles: pages.map((p) => p.title) };
}
console.log(JSON.stringify(summary, null, 1));
